### ISSUE TITLE
Error on Frontend

### ISSUE THREAD

**Issue by Moorst** [wrav/oembed#1]
I'm getting;

`Uncaught ReferenceError: $ is not defined at oembed.js?v=1543396115:15`

Is it possible to disable this being referenced on the frontend? I'm not using jQuery which I assume is this issue?

**Comment by reganlawton** [comment]
@Moorst I'll get a patch for this out soon. I might see too replacing jQuery with native Javascript.

**Comment by reganlawton** [comment]
@Moorst give [v1.0.2](https://github.com/wrav/oembed/releases/tag/1.0.2) a go. I replaced the jQuery with standard Javascript

**Comment by reganlawton** [comment]
I have realised from another issues (see #2) that your issue is that the code is actually getting loaded into the front end. The JS shouldn’t be loaded outside the CP.

I’m going to do another release in the next few hours to resolve this issue.

**Comment by reganlawton** [comment]
Ok so you should now not have the JS asset load on the frontend @Moorst 

See release [v1.0.3](https://github.com/wrav/oembed/releases/tag/1.0.3)

**Comment by Moorst** [comment]
Brilliant, thanks @reganlawton
