### ISSUE TITLE
Unable to set a webpage as a valid source URL (fallback to iframe) since v1.3.11 

### ISSUE THREAD

**Issue by juban** [wrav/oembed#101]
We're heavily using your excelent plugin for many projects.

Until version 1.3.10, it was possible to give any kind of url as a source for the Embed. In that case, the plugin was kindly switching to an iframe version.
There is an annoying regression since version 1.3.11 and the introduction of the FallbackAdapter. In that context, even if the source url is valid, it will result in a "Please check your URL." error and blank output in the templates.

The reason this is happening is related to a silent error thrown in the `embed` method of the OembedService class.
When the `$media = Embed::create($url, $options, $dispatcher);` is called with a standard webpage url, the resulting Embed object will give an empty result when calling `$media->getCode()`.
So the following code (line 84 and 85) will result in an exception:
```PHP
$dom = new DOMDocument;
$dom->loadHTML($media->getCode()); // exception here
```

Changing that part with the following code revert the previous plugin behavior and works well with "normal" embedable urls:
```PHP
$dom = new DOMDocument;
$code = $media->getCode();
if (empty($code)) {
    $code = Utils::iframe($media->url);
}
$dom->loadHTML($code);
```

I can send you a PR for that matter if it helps.

**Comment by juban** [comment]
@reganlawton 
Do you think it would be possible to push a tag for the fix soon? That would be really helpful to us. Thanks.

**Comment by reganlawton** [comment]
@juban that has now got a release tag.

**Comment by juban** [comment]
@reganlawton 
No worry, thank you so much for the new release, it will save us a lot of trouble.

**Comment by reganlawton** [comment]
@juban thanks for contributing
