### ISSUE TITLE
Exception thrown with Caching turned on

### ISSUE THREAD

**Issue by fantasticmachine** [wrav/oembed#104]
I think I'm seeing something related to [this issue](https://github.com/wrav/oembed/issues/101) but with version 1.3.15

With caching turned on in the plugin settings I am getting a "Please check you URL" error in the field and the following Exception on page:

`Serialization of 'DOMDocument' is not allowed`

```
1. in /srv/users/production/apps/production/vendor/yiisoft/yii2/caching/Cache.php at line 249
240241242243244245246247248249250251252253254255256257258    {
        if ($duration === null) {
            $duration = $this->defaultDuration;
        }
 
        if ($dependency !== null && $this->serializer !== false) {
            $dependency->evaluateDependency($this);
        }
        if ($this->serializer === null) {
            $value = serialize([$value, $dependency]);
        } elseif ($this->serializer !== false) {
            $value = call_user_func($this->serializer[0], [$value, $dependency]);
        }
        $key = $this->buildKey($key);
 
        return $this->setValue($key, $value, $duration);
    }
 
    /**

```

However this is only happening on my production server. Both staging and local dev are working OK.

Any ideas? We need to have caching on to prevent hitting YT's fair use limits.

**Comment by fantasticmachine** [comment]
UPDATE: This appears to be related to the PHP version.
Works OK on PHP 7.4 but throws the error on PHP 8.1

**Comment by reganlawton** [comment]
THis should be resolved in the 2.0.0 release soon

**Comment by tomkiss** [comment]
Hi @reganlawton -

I'm seeing this error on Craft 3 with version 2.0.0.

Is there any plan to fix on the 1.x release?

**Comment by reganlawton** [comment]
It's not possible 2.0.0 is branch for Craft v4 the composer.json shouldn't never let Craft v3 install cos the plug-in extended classes require PHP 8.0.2 minimum via Craft v4. This is why I set a MAJOR release and not a MINOR  version. It's weird that your trying to install v2.0.0 if your using Craft v3 🤔

**Comment by tomkiss** [comment]
Thanks @reganlawton 

Oh no, I'm still on `1.3.15` and wasn't trying to install `2.X`, it's just that I just noticed this error on PHP 8 and Craft 3. I've probably had the bug a while but just not noticed it before, although thankfully it doesn't affect many pages. 😬

**Comment by reganlawton** [comment]
I COULD let craft 3 would I believe but we'd need to be Craft v3 but with PHP 8 and I don't even know off the top of my head if that's supported haha. It's abit annoying cos it's only a few changes in the plug-in that actually impacted but PHP 8 😩 maybe one day I can look into issue but most people are looking at Craft v4 now so there's that to consider

**Comment by tomkiss** [comment]
Ok sure thing 🙌

**Comment by reganlawton** [comment]
I've found this stupid bug and "fixed" it in v2.x, AKA PHP 8 version, by converting the Embed class that gets cached from a Class to JSON string and back to StdClass, I think this will be the way to go. It snapshots the object but solves the issue. Don't know WHY it started happening, probably from the core package I use, but I'm sorry this took so long to "figure out" I've just been so under the pump. This will be resolved tomorrow, it's currently 1:45am here in Melbourne, AU but turning cache off for now resolves it.

**Comment by reganlawton** [comment]
Just to summary the v1 branch will be updated and tagged with a new v1.x version 🍻
