### ISSUE TITLE
Required field isn't verified on entry save

### ISSUE THREAD

**Issue by jamiematrix** [wrav/oembed#106]
Had a client break a page yesterday where they added the oEmbed field in but didn't populate the URL input. I tested on a local copy of the site and I'm able to save the entry even though the oEmbed field is marked as required.

In hindsight we probably should check the URL isn't empty before the field is rendered, but if it's marked as required surely the entry shouldn't save?

**Comment by reganlawton** [comment]
Can you let me know the version of Craft your using? That's very weird and seems like something I wouldn't have missed and might be a be something that came up that I didn't notice or a change made. It'll you can add some more information I can see what I can do to help you out.

**Comment by reganlawton** [comment]
Or if you've fou d the issue Is be happy to take a PR

**Comment by jamiematrix** [comment]
Apologies, should have included versions...

Craft is on  3.7.37
Plugin is on 1.3.15

The field lives inside a Matrix field if that helps.

If I find anything that might be the cause I'll comment here.

**Comment by reganlawton** [comment]
Oh matrix field! That legit helps so much more then your can believe.

**Comment by reganlawton** [comment]
I'll take a look at the issue in the morning.

**Comment by jamiematrix** [comment]
Morning? It's just gone mid-day here :)
As I have more waking hours I will try to have a dig to see if anything jumps out.

**Comment by reganlawton** [comment]
v2.2.0 (CraftCMS v4) and v1.3.18 (CraftCMS v3) tagged with `required` changes.
