### ISSUE TITLE
Craft 4?

### ISSUE THREAD

**Issue by angieherrera** [wrav/oembed#108]
Wondering if this plugin will get updated for Craft 4?

**Comment by bartrylant** [comment]
Same question! I use this plugin on nearly every website I develop as it is a very easy to use all-in-one plugin. This is the only plugin now holding me from upgrading to Craft 4 at the moment.

**Comment by reganlawton** [comment]
Yes I'm planning on a massive update with the `dev-embed4` composer tag. Thats been set to use the new embed/embed major version which no one has been testing which comes with a ton of fixes to oembed so I'm making time now that I've finished on a 3 month refactor.

I'm make sure that the Craft 4 go into that branch in future and start that shortly. This will give oembed a massive fresh update with a new major version.

**Comment by reganlawton** [comment]
Please give `"wrav/oembed": "dev-feature/craft-v4"` a test everyone are I got a few PHP 8 typing issues but the plugin does quite abit so if you see anything let me know. I'm using a draft PR here: https://github.com/wrav/oembed/pull/109

**Comment by reganlawton** [comment]
GraphQL will be needed to be tested abit more too

**Comment by reganlawton** [comment]
Any movement on reviews?

**Comment by justinholtweb** [comment]
I'll be able to do some local tests starting tomorrow (Thursday) on that release. I will post up right away on the results. Thanks for the quick resolution @reganlawton

**Comment by justinholtweb** [comment]
Makes sense and agreed. I have a big batch of site maintenance to finish tomorrow and the goal was moving them up to Craft 4, several use this plugin so will be a perfect time to stress test. Should have some feedback for you by the mid-afternoon Eastern time.

**Comment by bencroker** [comment]
Working great in my tests!!

**Comment by maxstrebel** [comment]
Tested it. No problems encountered yet.

**Comment by reganlawton** [comment]
v2.0.0 is out. Pray it goes well 😅
