### ISSUE TITLE
Facebook videos embed ?

### ISSUE THREAD

**Issue by migswd** [wrav/oembed#11]
Does it work with Facebook videos too ?
Like this : 
https://www.facebook.com/goalcast/videos/1503523589724826/

**Comment by reganlawton** [comment]
@migswd Why yes it does, I just tested your URL also so you can see it in action.

<img width="814" alt="Screenshot 2019-04-04 17 44 20" src="https://user-images.githubusercontent.com/2705875/55535056-be409c80-5701-11e9-861c-83f6af8ff249.png">

**Comment by migswd** [comment]
Thats fantastic ! :)

Also one last question : should I make a fieldtype oEmbed in Craft or can I use oEmbed twig render directly on a any link fieldtype ? Or we just can do both ?

**Comment by reganlawton** [comment]
Both are useable and has the same features

**Comment by migswd** [comment]
Awesome ! :)
Thank you for this great plugin !
