### ISSUE TITLE
Enabling the cache breaks the plugin under PHP 8.1+

### ISSUE THREAD

**Issue by amphibian** [wrav/oembed#113]
Just moved to a server running PHP 8.1.2, and with oembed's cache enabled, the plugin breaks.

```
Exception: Serialization of 'DOMDocument' is not allowed in /[...]/craftcms/vendor/yiisoft/yii2/caching/Cache.php:249
Stack trace:
#0 /[...]/craftcms/vendor/yiisoft/yii2/caching/Cache.php(249): serialize()
#1 /[...]/craftcms/vendor/wrav/oembed/src/services/OembedService.php(171): yii\caching\Cache->set()
```

Disabling the oembed cache fixes the issue.

**Comment by reganlawton** [comment]
@amphibian  I'm not having this issue can you provide me with the URL you're using that has the issue. If not it might be from the database and might be nice to contact and see if I can see what your DB is doing.

On that said what DB are you using? MySQL, Maria, Postgres?

**Comment by amphibian** [comment]
The URL doesn't help, as it simply returns an internal server error. This is applying to all videos embedded across the site, not just one in-particular.

I also cleared all caches in case there was an issue with cached data, but doing that and then turning the oEmbed cache on brought the error back.

Versions:

Craft 3.7.45.2
PHP 8.1.2
MySQL 8.0.29

**Comment by reganlawton** [comment]
Oh this is a v1 branch changes that's why I couldnt have the issue with it. I added PHP 8 support to v2 and Craft v4. I'll have to spin up a new project with Craft 3 and PHP 8 and see what I can fix

**Comment by reganlawton** [comment]
Try using `dev-bugfix/issue-113` it converts the Class to JSON and back to StdClass. The fields will be static and locked so if your using cache on you should use the following.

```twig
{{ entry.field.media.height|default }}
{{ entry.field.media.something|default }}
```

This will just left you handle bits you won't from a "live" response but URL and code should always be there as a minimum I believe.

Let me know how that goes.
