### ISSUE TITLE
FallbackAdapter is not handled correctly due to #101 fix

### ISSUE THREAD

**Issue by juban** [wrav/oembed#118]
@reganlawton 
There is a side effect to my bug fix : if no or wrong url is provided, the preview and embed now falls back to the default Craft site. I've fixed it successfully locally and hopefully provide a PR that will solve this in a satisfying manner.

**Comment by reganlawton** [comment]
A PR will be great thank you

**Comment by juban** [comment]
@reganlawton Just pushed one. I've bump composer version number to 2.2.1 and updated the change log.
Once again, feel free to modify or update that to your liking.
Thank you for your patience :)

**Comment by reganlawton** [comment]
The changelog and version bump makes PRs a dream. Im gonna have to basically make you a maintainer at this point haha

**Comment by juban** [comment]
@reganlawton Are you kidding? You did a tremendous job with this plugin which probably saved me hours. I'm sorry I don't have much time to provide a better contribution quality and I'm very grateful for your time.

Thank you for your hard work :)

**Comment by reganlawton** [comment]
Haha yeah it's in Top 10 for field plugins so it's good it's used. It's good to see more people sending in PRs. I made a team "Maintainers" I'm gonna like into GitHub permissions and see what I can do giving core people/ active maintainers more access to branches on the repo and lock down the main branches. That way it might help speed up bug fixes and new features and upgrades.
