### ISSUE TITLE
Disable on certain fields in control panel?

### ISSUE THREAD

**Issue by jcrichto** [wrav/oembed#12]
I'm currently running into an issue with oembed breaking another instagram plugin (https://picpuller.com/)

The script tag is breaking the picpull instagram field, see screenshot:
https://cl.ly/918deb9d6729

Is there any way to disable your plugin on certain field types?

**Comment by reganlawton** [comment]
Yep I can see what would be causing that I’ll try getting out a patch ASAP

**Comment by reganlawton** [comment]
@jcrichto Just release [v1.1.5](https://github.com/wrav/oembed/releases/tag/1.1.5) give that a try should resolve your issue.

**Comment by jcrichto** [comment]
Works great! Thanks for putting the patch out.
