### ISSUE TITLE
Loss of metadata when loading from cache on 2.2.x

### ISSUE THREAD

**Issue by lmcnearney** [wrav/oembed#120]
As part of version `2.2.0`, the metadata available during an initial request (like the `media.providers` and `media.images`) are no longer saved and returned when using the cache. This is likely due to the new JSON serialization happening in https://github.com/wrav/oembed/commit/e4bf0952a90ea95e4c22e098e40639b63c8e2c13 which appears to only serialize the 4 simple properties of the `OembedModel` class.

Is the change intended or an oversight? I use the metadata for a variety of uses cases.

**Comment by reganlawton** [comment]
This update was just a stop point. I'm looking into updates to the caching as the response property uses unserialisable class, which is coming from PHP 8.X so I'm looking into upgrade but wanted to give a simple solution that wasn't hard broken well I look into the issue.

**Comment by reganlawton** [comment]
Believe this was resolved in v2.3.0 using default cache key setting with cache prop option to cache none default keys
