### ISSUE TITLE
Youtube embed stopped working

### ISSUE THREAD

**Issue by bartrylant** [wrav/oembed#121]
When entering a YouTube url in an oembed field, I now get:

`Onze systemen hebben ongebruikelijk verkeer van uw computernetwerk vastgesteld. Probeer uw verzoek later opnieuw.
`
Instead of the embedded video.

This happens with oembed fields only. When I embed the YouTube video with another plugin or hardcode it. It does not give an error.

**Comment by reganlawton** [comment]
Is this from the preview? Or then the template? I'm not at computer ATM to translate the error message just will update when near a computer.

**Comment by CassadyBlake** [comment]
Is there anything we can do on the YouTube side(within our youtube settings) to allow authentication on a particular domain or IP(anything to get around the rate limit?)

**Comment by reganlawton** [comment]
@CassadyBlake have you turned on caching I'm in the oembed setting?

**Comment by CassadyBlake** [comment]
> @CassadyBlake have you turned on caching I'm in the oembed setting?

I have and I still get the same error

**Comment by CassadyBlake** [comment]
After making some other updates and deploying the site changes the videos work now. Perhaps this action resets the youTube rate limit? I have also enabled caching... so we will see if it happens again.

**Comment by reganlawton** [comment]
The rate limit is held for a few hours I believe. Unless you have something like an elastic IP pool and when you deploy the outgoing IP for your server changes.
