### ISSUE TITLE
Error when using entry.field.media.image

### ISSUE THREAD

**Issue by angieherrera** [wrav/oembed#123]
Hi! I am using this in a Matrix block and trying to pull the thumbnail via `entry.field.media.image`. It results in a Twig Runtime Error:

_Neither the property "image" nor one of the methods "image()", "getimage()"/"isimage()"/"hasimage()" or "__call()" exist and have public access in class "stdClass"._

Here's my relevant code:

```
{% if block.thumbnail|length %}
   {% set image = block.thumbnail.one() %}
   {% set thumbnail = craft.imager.transformImage(image, { width: 1000 }, { ratio: 16/9 }) %}
{% else %}
   {% set thumbnail = block.videoUrl.media.image %}
{% endif %}
```

This is on Craft 3.7.44 and oEmbed 1.3.18.

**Comment by reganlawton** [comment]
Do you have caching on?

**Comment by bartrylant** [comment]
It looks like there is no `media` data at all anymore? I'm using `entry.field.media.type` a lot. But when I have a YouTube video, this is now what's in the object:

```
^ {#3957 ▼
  +"url": "https://www.youtube.com/watch?v=KNf9QeIg7mc"
  +"width": 200
  +"height": 113
  +"code": "<iframe width="200" height="113" src="https://www.youtube.com/embed/KNf9QeIg7mc?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; ▶"
}
```

Looks like the media info is gone?

I'm on Craft Pro 4.2.3 and oEmbed 2.2.2

**Comment by maxstrebel** [comment]
> Do you have caching on?

Caching is on. But it shows a similar error without. Same is for GDPR.

**Comment by angieherrera** [comment]
> Do you have caching on?

Sorry, just getting back to this. No, caching is not on.

**Comment by steverowling** [comment]
I was having the same problems until I turned caching off, which resolved it for me. Craft 4.2.4, oEmbed 2.2.2

**Comment by angieherrera** [comment]
I disabled caching and it resolved as well.

**Comment by maxstrebel** [comment]
Unfortunately it is not resolved for me when I deactivate the cache

**Comment by helleholmsen** [comment]
Any update on this?

**Comment by reganlawton** [comment]
The issue with the core package `embed/embed` was having issues with "Serialization of 'domdocument' is not allowed", so I use a method of JSON serialise the object. This misses the fields that normally get resolved using the Embed adapter.

You can try using a branch I pushed [dev-feature/caching-issue](https://packagist.org/packages/wrav/oembed#dev-feature/caching-issue) which default caches number of fields and also give you the support to add additional non default fields.

This can be used like so

```twig
{{ 
      entry.oembed_field.render(
         {
            width: 640,
            height: 480,
         }, 
         [
            'cacheable_key'  {# custom field on the oembed object that isn't covered #}
         ]
      ) 
   }}
```

If I can get some review on the branch and check the README for me info or add questions here.

🤞

**Comment by petehjfd** [comment]
@reganlawton I just tested the dev-feature/caching-issue branch and it solved the issue perfectly for me.

Do you think we can get this into a release?

Thanks!

**Comment by reganlawton** [comment]
It's currently 1245pm but I can look into this in the morning. Thanks for giving the time to review it I seems like a much more robust caching strategy since the broke in previous PHP 7.X versions

**Comment by petehjfd** [comment]
Thanks @reganlawton, that would be great!

**Comment by reganlawton** [comment]
@petehjfd Updated in v2.3.0

**Comment by petehjfd** [comment]
Amazing, thanks @reganlawton!
