### ISSUE TITLE
oEmbed Stopped Pulling Data

### ISSUE THREAD

**Issue by jaredchesebro** [wrav/oembed#124]
I upgrade to 2.2.2 and then updated my Craft primary domain and for some reason I started getting a bunch of CSP issues. I didn't have time to troubleshoot so I stopped using your plugin.

**Comment by reganlawton** [comment]
@jaredchesebro CSP? Are you talking "Content Security Policy"?

If so there is nothing I can do there that seems like you have a policy blocking things. Nothing from the plugin handles security policies.

**Comment by reganlawton** [comment]
If you have a policy plugin that might need to be configured for IFRAMEs and external domains

**Comment by jaredchesebro** [comment]
After a little troubleshooting: basically what was happening was that the oEmbed field/twig tag started outputting malformed iframe src values and YouTube was blocking them. The only thing I did leading up to the issue was change from a staging domain to the live domain. Since I was launching the site I just didn't have time to dig into it further. I disabled the plugin and just wrote a macro to properly form the iframe.

**Comment by maxstrebel** [comment]
Hey, this just brought down a production site of mine. Is there any chance this can be investigated? Otherwise I also will need to replace the plugin.

**Comment by reganlawton** [comment]
I'll need more information to be able to help out here I'm afraid.

This could be the plugin side or the core `embed/embed` package itself or even the Content Security Policy itself. I'll need to see the code returned and the dev console logs to see what's going on here
