### ISSUE TITLE
Craft 4 embeds suddenly default to 200px wide iframe

### ISSUE THREAD

**Issue by joomkit** [wrav/oembed#126]
Using latest Craft 4 , PHP8.1
Adding some videos and noticed that the iframe produced is hardcoded 200px wide whereas it was 100% previously. IM rendering out of a partial matrix block like below
```
{{ block.video.render }}
{{ craft.oembed.render(url) }}
```

**Comment by TUSAB-web** [comment]
I am also having this issue. I am styling the iframe with CSS, but then it outputs its own style within the iframe which overrides my CSS.

**Comment by reganlawton** [comment]
Use can use the `attributes` option to change the width and height `<iframe/>` attributes

```twig
{{ craft.oembed.render(
        '<URL>',
        {
            params: {
                autoplay: 0,
            },
            attributes: {
                width: 640,
                height: 480,
            }
        }
    ) }}
```

Obviously CSS is also an option and might be the better option in most cases

**Comment by davidwebca** [comment]
Sorry to comment on this, but is there a way to add these attributes on a GraphQL query?

**Comment by reganlawton** [comment]
@davidwebca Thats a very good question 🤔 I'll have to spin up my demo project's docker container and play with Apollo Studio to refresh myself with the GQL side.

**Comment by reganlawton** [comment]
@davidwebca Thanks for commenting I found the issue. 

Initially I setup GQL for just metadata handling. I have spin up my demo container and updated GQL field handling habit, still working on it.

It seems I completely ignored the params handling as GQL support , which was just a Github issue request and I didn't use GQL when I started coding it in.

I'm gonna merge in `master` branch and create a branch for you to test called `dev-feature/gql-params` or something like that. I'll ping you again when I push that out and its ready for testing.

**Comment by reganlawton** [comment]
@davidwebca could you use Composer to try out [dev-feature/gql-params](https://packagist.org/packages/wrav/oembed#dev-feature/gql-params) branch. Might be early testing but  its coming into the weekend for me and want to try get some feedback that I can try out over the weekend.

**Comment by davidwebca** [comment]
Hi! Thanks so much for this! It works in principle, but I noticed three things : 

1. The test $url has been left hardcoded on OembedField.php:130
2. The raw width and height returned don't correspond to what we pass (when we pass them, I would expect them to be returned as is or what the oembed service returns)
3. The width is multiplied by two for some reason on OembedService.php:163.

For example, with this json-encoded string of options with width 800, height 800 and autoplay 1

```gql
oembedVideo(options:"{\"width\":1600,\"height\":900,\"autoplay\":1}") {
    url
    type
    image
    imageWidth
    imageHeight
    code
    width
    height
}
```

It yields

```json
"oembedVideo": {
  "url": "https://www.youtube.com/watch?v=S6dozy6euxc",
  "type": "video",
  "image": "https://i.ytimg.com/vi/S6dozy6euxc/hqdefault.jpg",
  "imageWidth": "480",
  "imageHeight": "360",
  "code": "<iframe width=\"3200\" height=\"900\" src=\"https://www.youtube.com/embed/S6dozy6euxc?autoplay=1&amp;feature=oembed\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen=\"\" title=\"Crush EVERYONE with the Alien Gambit!\"></iframe>",
  "width": "200",
  "height": "113"
}
```

**Comment by reganlawton** [comment]
@davidwebca I have merged your PR and yeah there is legacy handling in play which was something I was trying to update at the same time. Thats been updated if you think the changes are good I think we can run it thought. I do think I'll have to look into unit testing for this plugin cos so many sites use it. PHPUnit with Craft plugins are always a pest 😩

**Comment by davidwebca** [comment]
No worries. I've got the perfect test run, I'm running Craft 5 for a real client (site will be released close to 5's release). I'll let you know if I find issues and contribute as much as I can 🤘
