### ISSUE TITLE
Spotify embeds are only working in local environment

### ISSUE THREAD

**Issue by romainpoirier** [wrav/oembed#128]
I'm embeddding using this method, where `block.podcast` is an URL (within a Matrix) :
`{{ craft.oembed.render(block.podcast) }}`

This is working fine in my local environment, but on production the output remains empty (no code), so the embed is not displaying. 

Here's a Spotify URL: https://open.spotify.com/episode/1utnUPF9vBgV8zLFhlSlGf?si=a63215a1d4f047db
As a comparison, this Deezer URL is working both locally and on production: https://www.deezer.com/fr/show/5511427

I don't see any error in the Craft logs.

Any reason why and how to fix this?

**Comment by reganlawton** [comment]
This is normally caused due to a PHP config issue or a conflicting composer package issue. Normally around CURL
