### ISSUE TITLE
"Please check your URL" bug is back?

### ISSUE THREAD

**Issue by bartrylant** [wrav/oembed#129]
I noticed this error comes back quite a lot (many issues on this github). So here we go again:

Suddenly, out embedded YouTube video's didn't show up anymore. The render code just displays a white rectangle. This is what I found so far:

- When pasting a YouTube url in the oEmbed field, it says `Please check your URL.`
- When saving the entry anyway, the url gets saved, but the oembed object = null
- The `entry.field.media.providerName` is set to `google`

Not sure what is going on here but it's extremely annoying. It causes my clients website - which uses YouTube embeds quite a lot - to not display any embedded video from time to time. I have no idea what causes this. This all happens on production, not on dev. And when I embed the same video hardcoded (i.e. just use the iframe code generated by YouTube), the video displays without any problem. So it's an issue when converting the pasted url (in the field) to rendering.

PHP version | 8.1.12
Craft Pro 4.3.4
oEmbed 2.2.2

**Comment by denisyilmaz** [comment]
@kelenakamura 
inside `config/oembed.php` you can define if oembed should cache the responses for the embeds (which is causing this issue):

```php
<?php
return [
    '*' => [
        'enableGdpr' => true,
        'enableNotifications' => false,
        'enableCache' => false,
    ],
    'production' => [
        'enableCache' => true, // set this to false if the caching issue appears
    ],
];
```

**Comment by reganlawton** [comment]
I think it's time for me to revisit the embed package upgrade

**Comment by kelenakamura** [comment]
we found the issue - it was a php curl issue - we were getting a curl 77 error - so following this fixed it - https://github.com/guzzle/guzzle/issues/1935#issuecomment-371756738

**Comment by denisyilmaz** [comment]
@kelenakamura we run into that issue now ourself (even with disabled cache) and the newest oembed plugin version. Restarting php-fpm did not work.

**Comment by yoannisj** [comment]
hi @reganlawton ! I work with @denisyilmaz and it looks like this is related to some oEmbed providers not returning an `<iframe>` in the HTML by default –in our case [Issuu.com](https://issuu.com/).

In those cases, a "Call to a member function getAttribute() on null" error is thrown https://github.com/wrav/oembed/blob/master/src/services/OembedService.php#L121 but that error is not handled and we don't get a `FallbackAdapter`.

---

The Issuu.com [oEmbed endpoint](https://developer.issuu.com/oembed#request) supports an `iframe=true` query argument which forces it to return the embed code as an `<iframe>`. Looking at the source code ([here](https://github.com/wrav/oembed/blob/master/src/services/OembedService.php#L82) and [here](https://github.com/oscarotero/Embed/blob/master/src/OEmbed.php#L68)) it seems I should be able to pass that query argument to the Issuu oEmbed endpoint like so:

```
{% set media = craft.oembed.embed(url, {
    `oembed:query_parameters`: {
        iframe: true,
     }, 
 }) %}
 
 {{ media.code |raw }} {# AFAIK this should now include an iframe #}
```

However, that does not work and I can't figure out why...

To my greatest surprise: I get an empty array when I dump `$this->extractor->getSettings()` [here](https://github.com/oscarotero/Embed/blob/master/src/OEmbed.php#L68), although  I can see the `'oembed:query_parameters'` option when I dump `$infos->getSettings()` [here](https://github.com/wrav/oembed/blob/master/src/services/OembedService.php#L82)).

**Comment by reganlawton** [comment]
@yoannisj and @denisyilmaz I believe this is the issue from #141 where the TRY CATCH was getting the wrong exception and I wasn't fallback.

If you can try v2.3.2 Im just about to tag it

**Comment by yoannisj** [comment]
@reganlawton can you confirm that passing a map with key 'oembed:query_parameters` as 2nd argument `$options.oembed:query_parameters` key for `wrav\embed\OembedService::embed($url, $options)` should include that map as query parameters to the oembed endpoint?

If that's the expected behaviour, it does not seem to be working. Is that something you could look into?

**Comment by yoannisj** [comment]
Of course, this is the URL I have been testing with: `@web/admin/oembed/preview?url=https://issuu.com/deignismedia/docs/64_deignis_magazin_web`. Thanks, and have a good night!

**Comment by reganlawton** [comment]
Awesome thanks for that @yoannisj that'll great help my testing.

Fingers crossed we have this resolved tomorrow 🤞

**Comment by reganlawton** [comment]
@yoannisj Seems the embed/embed v3.x doesn't issuu.com, I can definitely resolved the issue in v3.0.5. So seeing your using the news version track (v3) you should be fine.

Im about to tag it so please update and let me know.  This is the code I used to test.

```twig
{{
    craft.oembed.render(
        'https://issuu.com/deignismedia/docs/64_deignis_magazin_web',
    )
}}
```

**Comment by yoannisj** [comment]
@reganlawton did you manager to pass on query parameters to the oEmbed endpoint called by `embed/embed` using the 2nd argument for the `wrav\embed\OembedService::embed($url, $options)` method?

We are retrieving the oembed information via GraphQL, which uses the oEmbed field value (i.e. `craft\base\Element::getFieldValue('oembedFieldHandle')` which in turn relies on `wrav\embed\OembedService::embed($url, $options)` so we would need a way to modify the underlying oembed request.

How would you feel about triggering an event in the `wrav\embed\OembedService::embed` method so custom modules/plugins can modify the options given to embed/embed programmatically? That sounds very useful in case other oEmbed services (not just issuu) rely on query arguments to return iframes in the oembed html code. 

Note that Issuu used to work for us, and stopped so I suspect they changed the behaviour of their oEmbed endpoint and that could happen to other services in the future. An event could mitigate this risk, and provide a way for projects to fix it without depending on a new `wrav/oembed` release.

**Comment by reganlawton** [comment]
@yoannisj the code I provided in  previous comment worked as intended without need for params / options.

**Comment by reganlawton** [comment]
Try using the latest version if you haven't already

**Comment by reganlawton** [comment]
@yoannisj Oh shit sorry I completely offer looked the GQL bit 😅 I'll have  to test that.

As for adding custom adapters, there is definitely a way I can do that I just haven't cos it's more code I have to manage. If creating a custom adapter based on options is something you'd like me to look into. I definitely can. I would probably allow you to be able pass a class. fat class would then be what is used given you their ability to completely customise your code.

**Comment by reganlawton** [comment]
@yoannisj Lots of updates out with v3.0.6 this should fix issues with GraphQL.
