### ISSUE TITLE
Caching issue

### ISSUE THREAD

**Issue by stefanmf** [wrav/oembed#13]
It seems that Craft's caching is not playing well when embedding with options, at least from Vimeo.
I have the following code:
```
{% set options = {'oembed' : {'parameters' : {'color': 'FF0000', 'byline': 0, 'portrait': 0, 'title': 0, 'width': '800px'}}} %}
{{ craft.oembed.render(field.media.url, options) }}
```
The options are ignored (video displayed with default values). I tried removing the following code from the embed function in OembedService.php:
```
if (Craft::$app->cache->exists($url)) {
    return \Craft::$app->cache->get($url);
}
```
After removing the above code, the options are working and the video is displaying as expected. Clearing the Craft cache does not fix the problem.

**Comment by reganlawton** [comment]
@stefanmf I think I’ll add a option to set off caching and then look into this issues further

**Comment by reganlawton** [comment]
@stefanmf You should be able to now disable caching.

https://github.com/wrav/oembed/releases/tag/1.1.6
