### ISSUE TITLE
Video preview very small

### ISSUE THREAD

**Issue by migswd** [wrav/oembed#133]
I got my oembed video preview in CP working fine but it is very small.
Is it normal?
Could we make it bigger?
![CleanShot 2023-02-20 at 15 16 30@2x](https://user-images.githubusercontent.com/3531623/220132560-b48a16b8-7880-4959-b47b-169d68b7908a.jpg)

**Comment by reganlawton** [comment]
Hmm I think maybe a custom CSS option in the settings will be the way to be here 🤔 

I can't just use 100% width but maybe I can width 100% with a width max of 640px?

**Comment by reganlawton** [comment]
You can also use

```twig
{{
    entry.field_media.render({
        attributes: {
            width: 1000,
            height: 500
        },
    })
}}
```
