### ISSUE TITLE
Field always renders as if it has content

### ISSUE THREAD

**Issue by matanlevkowich** [wrav/oembed#137]
I have been trying to do something very simple with the plugin but it keeps failing and I suspect that it is a bug.

 I have an oEmbed field with the handle `videoUrl`. I am trying to do something very basic - to test if the field is empty.

I am not sure why it fails. I have tried all the following codes on an empty field but it keep rendering the content despite the fact that the field is empty...
`{% if entry.videoUrl is not empty %}
    <div class="page orange">
        <div class="video">
            {{ craft.oembed.render(entry.videoUrl, {params: {title: 0, portrait: 0, byline: 0 }}) }}
        </div>
    </div>
{% endif %}`

`{% set video = entry.videoUrl %}
{% if video is defined and video is not empty %}
    <div class="page orange">
        <div class="video">
            {{ craft.oembed.render(entry.videoUrl, {params: {title: 0, portrait: 0, byline: 0 }}) }}
        </div>
    </div>
{% endif %}`

`{% if entry.videoUrl|length %}
    <div class="page orange">
        <div class="video">
            {{ craft.oembed.render(entry.videoUrl, {params: {title: 0, portrait: 0, byline: 0 }}) }}
        </div>
    </div>
{% endif %}`

`{% set video = entry.videoUrl ?? null %}
{% if video %}
    <div class="page orange">
        <div class="video">
            {{ craft.oembed.render(video, {params: {title: 0, portrait: 0, byline: 0 }}) }}
        </div>
    </div>
{% endif %}`

Not sure why this simple validation doesn't work with this plugin...

**Comment by reganlawton** [comment]
There is  `craft.oembed.valid(url, options, cacheFields)` and `entry.field.valid` handling for validation. Calling the field itself will return object as the plugin has a fallback for websites that cant find rich media / oembed data.

The reason I guess your having issues is the admin panel field handles a url but always returns a object thats why the valid methods and twig variable was made.

**Comment by reganlawton** [comment]
Closing but can reopen if more discussion needed
