### ISSUE TITLE
Field causes template to crash if left blank

### ISSUE THREAD

**Issue by laurabennett** [wrav/oembed#138]
I'm getting an internal server error and can't get to the edit screen at all!
v2.3.0
craft 4.5.6.1
Declaration of wrav\oembed\jobs\BrokenUrlNotify::execute($queue) must be compatible with craft\queue\JobInterface::execute($queue): void

I was so excited this was going to work and when I moved it up to live site I can't even get to the edit screen for my homepage in the admin console.

**Comment by reganlawton** [comment]
Hmm that seems to have auto marked this issue as closed. @laurabennett if your able to check out the new v2.3.1 and if this resolved great if not ping me back I'll get right back to it. If you need to prevent this just turn of the enable notification in the plugin setting.

Sorry for the delay I've been moving to another state and it's been crazy. Thank you for your time to reach out and submit a issue

**Comment by reganlawton** [comment]
Glad to hear 👏
