### ISSUE TITLE
Issue when using oEmbed in Vizy block

### ISSUE THREAD

**Issue by holiday-jan** [wrav/oembed#141]
- CraftCMS: 4.5.10 (env: production)
- Vizy: 2.1.12
- oEmbed 3.0.0 (version 2.3.0 has no issue, so reverting back for now)

Plugin settings oEmbed: **"Enable Cache" => on**

Trace log:
`
"#0 ./vendor/wrav/oembed/src/models/OembedModel.php(157): wrav\\oembed\\services\\OembedService->embed()",
"#1 ./vendor/wrav/oembed/src/fields/OembedField.php(190): wrav\\oembed\\models\\OembedModel->embed()",
"#2 ./vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(273): wrav\\oembed\\fields\\OembedField->getInputHtml()",
"#3 ./vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(235): craft\\fieldlayoutelements\\CustomField->inputHtml()",
"#4 ./vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(222): craft\\fieldlayoutelements\\BaseField->formHtml()",
"#5 ./vendor/craftcms/cms/src/web/View.php(1669): craft\\fieldlayoutelements\\CustomField->craft\\fieldlayoutelements\\{closure}()",
"#6 ./vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(223): craft\\web\\View->namespaceInputs()",
"#7 ./vendor/craftcms/cms/src/models/FieldLayout.php(738): craft\\fieldlayoutelements\\CustomField->formHtml()",
"#8 ./vendor/craftcms/cms/src/web/View.php(1663): craft\\models\\FieldLayout->craft\\models\\{closure}()",
"#9 ./vendor/craftcms/cms/src/models/FieldLayout.php(737): craft\\web\\View->namespaceInputs()",
"#10 ./vendor/verbb/vizy/src/fields/VizyField.php(973): craft\\models\\FieldLayout->createForm()",
"#11 ./vendor/verbb/vizy/src/fields/VizyField.php(273): verbb\\vizy\\fields\\VizyField->_getBlocksForInput()",
"#12 ./vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(273): verbb\\vizy\\fields\\VizyField->getInputHtml()",
"#13 ./vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(235): craft\\fieldlayoutelements\\CustomField->inputHtml()",
"#14 ./vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(222): craft\\fieldlayoutelements\\BaseField->formHtml()",
"#15 ./vendor/craftcms/cms/src/web/View.php(1669): craft\\fieldlayoutelements\\CustomField->craft\\fieldlayoutelements\\{closure}()",
"#16 ./vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(223): craft\\web\\View->namespaceInputs()",
"#17 ./vendor/craftcms/cms/src/models/FieldLayout.php(738): craft\\fieldlayoutelements\\CustomField->formHtml()",
"#18 ./vendor/craftcms/cms/src/web/View.php(1663): craft\\models\\FieldLayout->craft\\models\\{closure}()",
"#19 ./vendor/craftcms/cms/src/models/FieldLayout.php(737): craft\\web\\View->namespaceInputs()",
"#20 ./vendor/craftcms/cms/src/controllers/ElementsController.php(864): craft\\models\\FieldLayout->createForm()",
"#21 ./vendor/craftcms/cms/src/controllers/ElementsController.php(449): craft\\controllers\\ElementsController->_prepareEditor()",
"#22 [internal function]: craft\\controllers\\ElementsController->craft\\controllers\\{closure}()",
"#23 ./vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(121): call_user_func()",
"#24 ./vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(49): craft\\web\\CpScreenResponseFormatter->_formatTemplate()",
"#25 ./vendor/yiisoft/yii2/web/Response.php(1100): craft\\web\\CpScreenResponseFormatter->format()",
"#26 ./vendor/craftcms/cms/src/web/Response.php(337): yii\\web\\Response->prepare()",
"#27 ./vendor/yiisoft/yii2/web/Response.php(340): craft\\web\\Response->prepare()",
"#28 ./vendor/yiisoft/yii2/base/Application.php(390): yii\\web\\Response->send()",
"#29 ./web/index.php(26): yii\\base\\Application->run()",
"#30 {main}"`

**Issue:**
`"exception":"[object] (Error(code: 0): Attempt to assign property \"title\" on null at ./vendor/wrav/oembed/src/services/OembedService.php:212)\n[previous exception] [object] (Error(code: 0): Call to a member function getCode() on null at ./vendor/wrav/oembed/src/services/OembedService.php:111)\n[previous exception] [object] (Embed\\Http\\NetworkException(code: 3):  at ./vendor/embed/embed/src/Http/CurlDispatcher.php:158)"`

**Comment by reganlawton** [comment]
@holiday-jan Hmm this is weird for context I run the following code:

```twig
{% for node in entry.vField.all() %}
    {% if node.type == 'vizyBlock' %}
        {% if node.handle == 'richText' %}
            <div>
                {{ node.media.render() }}
            </div>
        {% else %}
             Render other block types
        {% endif %}
    {% elseif node.type == 'paragraph' %}
        {% for nodeContent in node.content %}
            <p class="p-text">{{ nodeContent.text }}</p>
        {% endfor %}
    {% else %}
        {{ node.renderHtml() }}
    {% endif %}
{% endfor %}
```

I run with cache on. FYI `media` is the field slug.

My thinking is that the field was run in fallback mode but the weird thing is `OembedService.php:212` the code is in a try catch block

```php
foreach ($cacheKeys as $key) {
    try {
        $media->{$key} = $media->{$key};
    } catch (\Exception $e) {
        $media->{$key} = null;
    }
}```

If the key not found it it should return null but it seems that the issue is the `$media` variable is completely NULL itself.

```php
catch (InvalidUrlException $e) {
```

That code should catch invalid URL issues so I'm wondering if there is another exception all together and thats why its failing.

Would you be able URL so I can test BUT I'll update the exception to fail all bugs into a fallback state using

```php
} catch (Exception $e) {
```

I believe this should resolve but I'd love to test more but without more info I this its just a edge case in the exception handling with the `embed/embed` package upgrade

**Comment by reganlawton** [comment]
@holiday-jan Can you give v3.0.1 a go?

**Comment by holiday-jan** [comment]
Hi Regan!,
It's working perfectly, thank you very much.
Best regards, Jan
