### ISSUE TITLE
Looping a video

### ISSUE THREAD

**Issue by holiday-jan** [wrav/oembed#146]
Hi Regan,

We're using a video that we want to loop continuously. According to the [Google YouTube docs](https://developers.google.com/youtube/player_parameters#Parameters), Parameter: `loop`:
> Note: This parameter has limited support in IFrame embeds. To loop a single video, set the loop parameter value to 1 and set the [playlist](https://developers.google.com/youtube/player_parameters#playlist) parameter value to the same video ID already specified in the Player API URL: https://www.youtube.com/embed/VIDEO_ID?playlist=VIDEO_ID&loop=1

Is there an option we can use so the "playlist" is set to the same **VIDEO_ID**, but only when `loop=1` ?

Thank you in advance!
Beste regards, Jan

**Comment by reganlawton** [comment]
You can just add it to the params object and it'll add to the URL just like the loop

**Comment by holiday-jan** [comment]
Ok, only the `VIDEOID` is dynamicly fetched from the URL in the oEmbed field. So is it possible to implement this in the plugin? Because each oEmbed field can have different URL's, or the given URL can change in the future.

**Comment by reganlawton** [comment]
What's the playlist you're trying? Or will any playlist be fine to test? I'll give it a go in the morning.

**Comment by holiday-jan** [comment]
> What's the playlist you're trying?

The same as the given VIDEOID, from the Google YouTube docs:

> To loop a single video, set the loop parameter value to 1 and set the [playlist](https://developers.google.com/youtube/player_parameters#playlist) parameter value to the same video ID already specified in the Player API URL: https://www.youtube.com/embed/VIDEO_ID?playlist=VIDEO_ID&loop=1

So when the URL in the oEmbed field is: `https://youtu.be/Vol0KTIE2O8` or `https://www.youtube.com/watch?v=Vol0KTIE2O8` and we render it with:
`
{{ video.render({
    params: {
        autoplay: 1,
        controls: 0,
        mute: 1,
        loop: 1
    }
}) }}
`

We get:
`<iframe width="200" height="113" src="https://www.youtube.com/embed/Vol0KTIE2O8?loop=1&amp;mute=1&amp;controls=0&amp;autoplay=1&amp;feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen="" title="Strandpark de Zeeuwse Kust film"></iframe>`

We would also like the `playlist` param with the same `[VIDEOID]` as in the URL. In this example **`Vol0KTIE2O8`**, then it repeats over and over again ;),. else it stop after 1 cycle.

**Comment by reganlawton** [comment]
@holiday-jan I updated the docs and handling of the the `iframe` handling of saving the XML changes. I still need to update the support of the `params` prop again I honestly just don't know what happened with that.

**Comment by reganlawton** [comment]
@holiday-jan Found issues with the src handling and also added support for the playlist when `loop=1` is found

**Comment by holiday-jan** [comment]
Works perfectly! 👍
