### ISSUE TITLE
possible to display Youtube thumbnail before user gives cookie consent?

### ISSUE THREAD

**Issue by arentsen** [wrav/oembed#153]
Is it possible to display a youtube thumbnail using this plugin? I have a cookie banner which blocks the youtube video until the user gives consent for marketing cookies. I would like to display the Youtube thumbnail however so the layout of the page is not broken. Any tips would be appreciated.

**Comment by reganlawton** [comment]
@arentsen you should be about to user `.image` no?

**Comment by arentsen** [comment]
That variable did not give me anything. I did find a work around for YouTube. I used:

```
{% set thumbnail = "https://i.ytimg.com/vi/" ~ youtube_id ~ "/maxresdefault.jpg" %}
<img src="{{ thumbnaill }}">
```

Then I dumped the media variable `{{ dump(entry.field.media.data) }}` and found out that I could use the key `thumbnail_url` which did work.
