### ISSUE TITLE
Slow Twig Rendering Times

### ISSUE THREAD

**Issue by mattrothenberg** [wrav/oembed#16]
Howdy!

I've noticed a trend where entries on my site that are using `embed` fields inside of a matrix block are taking a _very_ long time to load. Here's a screenshot, for example, of a nearly 8 second render time for an article with a single embed of a CNN video.

<img width="388" alt="Screen Shot 2019-08-04 at 10 28 31 PM" src="https://user-images.githubusercontent.com/5148596/62434681-4615d200-b707-11e9-894e-ba02e0e31cc1.png">

These slow rendering times seem pretty deterministic. The only solution I've found has been to cache the article itself, which definitely helps.

I'm curious, though, whether you can think of any opportunities for optimization here on the PHP/Twig side of things.

One thing that would be cool, too, is if users could pass a custom class to the `iframe` that gets rendered by Twig, e.g., `lazyload` if you're using the [`lazysizes`](https://github.com/aFarkas/lazysizes) plugin, as well as being able to specify `data-src` instead of `src`.

Any ideas would be greatly appreciated!

**Comment by reganlawton** [comment]
@mattrothenberg Hmm are you able the link your using? I had an update in [1.1.6](https://github.com/wrav/oembed/blob/master/CHANGELOG.md#116---2019-04-22) , which made caching on the oEmbed side an optional feature, previously was always enabled.

This might be the issue your running into, as the plugin does offer support to cache the record on the PHP side.

**Comment by mattrothenberg** [comment]
Oooh, I totally missed that in the `changelog`.

For example, here are two pages that were super slow to render prior to using the `%cache%` tag.

1. https://passivehouseaccelerator.com/articles/passive-without-compromise-passive-house-design-improving-architectural-practice
2. https://passivehouseaccelerator.com/articles/cnn-covers-passive-house-these-100-year-old-homes-are-on-the-cutting-edge-of-energy-efficiency

**Comment by reganlawton** [comment]
That might be your servers networking. It loaded decently fine for me if you use the caching option id should be cached from the time you load the URL in the CMS admin area.

**Comment by mattrothenberg** [comment]
Roger that. Seeing as it's entries with embeds that are consistently the
slowest to load, I think it's less a question of overall networking.

Both of those pages had been cached for at least a few days now, hence the
fast load time. Will give that option a try.

Thanks for the prompt response!

**Comment by spoeken** [comment]
Hey @mattrothenberg , did you find a solution to this? Or an explanation why its slow?

**Comment by mattrothenberg** [comment]
@spoeken Sorry, I have no recollection of working on this 🙈

**Comment by spoeken** [comment]
@mattrothenberg haha, ok 😄 thank you
