### ISSUE TITLE
After Update to Craft 3.2.10 the media call is unrecognized

### ISSUE THREAD

**Issue by gudehus** [wrav/oembed#18]
After Update to Craft 3.2.10 the media call is unrecognized. I got this error on all lines that uses the media object.
Calling unknown method: craft\elements\MatrixBlock::media()
```
{% for movie in movies %}
    {% set ratio = (movie.source.media.width / movie.source.media.height)|round(2) * 100 %}
    <li class="landscape embed r_{{ ratio }}">{{ movie.source.render }}</li>
{% endfor %}
```

**Comment by reganlawton** [comment]
This only happened when updating to Craft 3.2.10? Were any other plugins updated? What version of the plugin are you using?

**Comment by reganlawton** [comment]
@gudehus also is says that the your calling media on a matrix block not a penned field. Are you sure your referencing the correct field / sub field?

**Comment by gudehus** [comment]
This is the list of installed PlugIns.


Asset Usage
2.0.1

Cookies
1.1.11

Element Map
1.2.1

Enupal Translate
1.2.0

Many to Many Field Type
1.0.2.2

Minifier
2.0.1

Olivemenus
1.0.9

Redactor
2.3.3.2

Redirect plugin for Craft 3
1.0.23

SEOmatic
3.2.20

SearchExcerpt
1.3.1

Site Switcher
2.1.0

Typogrify
1.1.18

oEmbed
1.1.6



Updated was only craft itself




mit freundlichen Grüßen
Jörg Gudehus

IT-Consultant

Holsteinische Straße 4
10717 Berlin
+49 151 15674619
gudehus@mac.com
www.joerggudehus.de


Pflichtinformationen gemäß Artikel 13 DSGVO
Im Falle des Erstkontakts sind wir gemäß Art. 12, 13 DSGVO verpflichtet, Ihnen folgende datenschutzrechtliche Pflichtinformationen zur Verfügung zu stellen: Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre personenbezogenen Daten nur, soweit an der Verarbeitung ein berechtigtes Interesse besteht (Art. 6 Abs. 1 lit. f DSGVO), Sie in die Datenverarbeitung eingewilligt haben (Art. 6 Abs. 1 lit. a DSGVO), die Verarbeitung für die Anbahnung, Begründung, inhaltliche Ausgestaltung oder Änderung eines Rechtsverhältnisses zwischen Ihnen und uns erforderlich sind (Art. 6 Abs. 1 lit. b DSGVO) oder eine sonstige Rechtsnorm die Verarbeitung gestattet. Ihre personenbezogenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen – insbesondere steuer- und handelsrechtliche Aufbewahrungsfristen – bleiben unberührt. Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Ihnen steht außerdem ein Recht auf Widerspruch, auf Datenübertragbarkeit und ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu. Ferner können Sie die Berichtigung, die Löschung und unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten verlangen. 
Details entnehmen Sie unserer Datenschutzerklärung (https://joerggudehus.de/dsgvo.html).

Hier können Sie sich AnyDesk zur Fernwartung herunterladen

https://get.anydesk.com/BEI2iuF8/AnyDesk-gudehus.dmg

**Comment by gudehus** [comment]
It is correct. Everything worked fine till the update.

mit freundlichen Grüßen
Jörg Gudehus

IT-Consultant

Holsteinische Straße 4
10717 Berlin
+49 151 15674619
gudehus@mac.com
www.joerggudehus.de


Pflichtinformationen gemäß Artikel 13 DSGVO
Im Falle des Erstkontakts sind wir gemäß Art. 12, 13 DSGVO verpflichtet, Ihnen folgende datenschutzrechtliche Pflichtinformationen zur Verfügung zu stellen: Wenn Sie uns per E-Mail kontaktieren, verarbeiten wir Ihre personenbezogenen Daten nur, soweit an der Verarbeitung ein berechtigtes Interesse besteht (Art. 6 Abs. 1 lit. f DSGVO), Sie in die Datenverarbeitung eingewilligt haben (Art. 6 Abs. 1 lit. a DSGVO), die Verarbeitung für die Anbahnung, Begründung, inhaltliche Ausgestaltung oder Änderung eines Rechtsverhältnisses zwischen Ihnen und uns erforderlich sind (Art. 6 Abs. 1 lit. b DSGVO) oder eine sonstige Rechtsnorm die Verarbeitung gestattet. Ihre personenbezogenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen – insbesondere steuer- und handelsrechtliche Aufbewahrungsfristen – bleiben unberührt. Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Ihnen steht außerdem ein Recht auf Widerspruch, auf Datenübertragbarkeit und ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu. Ferner können Sie die Berichtigung, die Löschung und unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten verlangen. 
Details entnehmen Sie unserer Datenschutzerklärung (https://joerggudehus.de/dsgvo.html).

Hier können Sie sich AnyDesk zur Fernwartung herunterladen

https://get.anydesk.com/BEI2iuF8/AnyDesk-gudehus.dmg

**Comment by reganlawton** [comment]
It’s saying that the “movie.source” field is a matrix block not a oembed field. So it’s not the plugin. I’d say run movie.source|dump to get more information and see what’s going on.

Because the error you state about says to me that your referencing the oembed field on the level up from the oembed field, which is inside a matrix block.

If your able to provide a screenshot here or at my email reganlawton92@gmail.com of your matrix block setup I might be able to provide some information of what might be wrong.

**Comment by reganlawton** [comment]
@gudehus did you get a chance to see if this was cos you were calling the matrix block ad ot the oembed field?
