### ISSUE TITLE
JS file placement and console error in 1.0.2

### ISSUE THREAD

**Issue by neokoenig** [wrav/oembed#2]
I guess this is two things but related?

1) the `<script src='http://domain.com/cpresources/52b8ecf8/oembed.js?v=1544072154'></script>` link appears outside the `<html>` tag, which I'm pretty sure is invalid HTML - is that to do with my front end?

2) it also throws:
```
oembed.js?v=1544072154:18 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at oembed.js?v=1544072154:18
    at Array.forEach (<anonymous>)
    at oembed.js?v=1544072154:17
(anonymous) @ oembed.js?v=1544072154:18
(anonymous) @ oembed.js?v=1544072154:17
```
in the console.

I can't help feeling that we should have an option to not include JS from `cpresources` too, and include it from the front end `@webroot` assets folder, even if it does then require an extra step?

**Comment by reganlawton** [comment]
I agree, an optional switch to disable the live preview JavaScript might be the solution here. I’ll add additional support you error handling. I’ll try have a new version out within the next day.

**Comment by neokoenig** [comment]
If it's only for the live preview, then could we not test for the equivalent of `{% if currentUser %}` ? (sorry, new to Craft) - at the moment it's then even if not logged in.

**Comment by reganlawton** [comment]
Sorry I think I’m understanding the issue and this might be related to issue #1. Is the JavaScript being included in the front end?

As it should only be injected in the admin portal. If this is the case it’ll be an easy fix. In the morning.

**Comment by neokoenig** [comment]
Ah right - that's correct, related to #1 then!

**Comment by reganlawton** [comment]
Ok seems to be the case that the JS is losing outside the control panel should be an easy fix will resolve today and have a patch in the next few hours.
