### ISSUE TITLE
Ajax embed preview doesn't work if you change the cpTrigger setting

### ISSUE THREAD

**Issue by mlathrom** [wrav/oembed#20]
Since the path to templates is hardcoded in the AJAX request, if you change the admin url, then the live preview doesn't work.

**oembed.js**
```
$.ajax({
    type: "GET",
    url: "/admin/oembed/preview?url=" + val + "&options[]=",
    async: true
}).done(function (res) {
```

**Comment by reganlawton** [comment]
Argh! This is a great point I’ll update this.

**Comment by reganlawton** [comment]
Resolved in v1.1.7

**Comment by mlathrom** [comment]
Nice! Great plugin, man. Thanks for the hard work.

**Comment by reganlawton** [comment]
@mlathrom no issues thanks for the bug report.
