### ISSUE TITLE
Adding to querysting of media.url when using render method.

### ISSUE THREAD

**Issue by johnniefp** [wrav/oembed#24]
Been looking through the issues on this damn handy plugin and cannot find an equivalent issue.

Problem I have is when a video is paused or finished YouTube throws up related videos, nice if you're browsing but not nice if your company video is displaying your competing company video after viewing.

I've got around this in the past appending adding '**&rel=0**' to to the youTube url path as shown below using your embed code with rel=0 added. (rel=0 sets '_show related videos_' to show related videos that are from the same channel as the video that was just played.)

`<iframe width="770" height="433" src="https://www.youtube.com/embed/LXb3EKWsInQ?feature=oembed&rel=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

Ideally we'd be able to add to the querystring using another param of the render method it looks like it's a passthru for $media->code.

Any pointers on how I best to do this with native oembed, tried without success so far.

**Comment by reganlawton** [comment]
I recently added a way to do this. I’ll extend the plugin to support the ‘rel’ option.

**Comment by reganlawton** [comment]
@johnniefp  The `rel`  is now supported in v1.2.1
