### ISSUE TITLE
FR: GraphQL Support?

### ISSUE THREAD

**Issue by wuhhh** [wrav/oembed#25]
Hi, unless I am missing something, it seems only the user input embed URL is exposed to graphql. Since gql support in Craft is now native, do you have plans to support this and expose all data?

Thanks

**Comment by reganlawton** [comment]
Yeah GraphQL support should be coming. I'm hoping to get some time soon to get a heap of new features out for the plugin, with the XMAS break just around the corner.

**Comment by reganlawton** [comment]
@wuhhh You should be able to use GraphQL in v1.2.0 and there is documentation on usage and I recommend using the cache feature hidden in the plugin settings.

**Comment by wuhhh** [comment]
Lovely, just did a quick test and working well :)

**Comment by reganlawton** [comment]
@wuhhh Thanks for the feedback and my deepest apology on the length of action on this issues. I plan to assign more support time to my plugins in the future.
