### ISSUE TITLE
Undefined index: autoplay

### ISSUE THREAD

**Issue by hannahwoodward** [wrav/oembed#26]
After performing some routine CMS & plugin updates on Craft, Sentry has started reporting an error for the oembed plugin, happening from both editing an entry and in the templates on entries that are using the oembed field.

https://sentry.io/share/issue/c4683affddff40c3bdcaad1ce37dffd7/
https://sentry.io/share/issue/d67205af7c234e058c4672eaf199ecf8/

Plugins updated:
- Craft (3.3.18.3)
- Sentry (1.0.2)
- Seomatic (3.2.37)
- Freeform (3.5.8)

Craft Version: 3.3.18.3
oEmbed Version: 1.1.8

**Comment by reganlawton** [comment]
I can see the issue here it’s that the array key is being called. A quick quick is to past auto play as an option till I can rest a new version tomorrow with the required empty() check.

**Comment by hannahwoodward** [comment]
Thanks! The site hasn't broken so it's not super urgent, just thought I'd forward on the error.

**Comment by reganlawton** [comment]
Argh I think I might it’s cos I put it in a try-finally and not handling the catch. It still needs to be fixed regardless I have time assigned over the holidays to make a few updates to all my plugins.

**Comment by hannahwoodward** [comment]
Any update on this?

**Comment by reganlawton** [comment]
@hannahwoodward  I'm truely sorry about this! I was working completely over the holidays due to a crazy project, even XMAS 😅

I'll try get this attacked tonight!

**Comment by reganlawton** [comment]
@hannahwoodward I've pushed out a release v1.2.0 which should have you issue resolved.
