### ISSUE TITLE
Facebook video mute when playing

### ISSUE THREAD

**Issue by migswd** [wrav/oembed#30]
Is there a way to make Facebook embedded videos unmute when we click PLAY?
Because now the Facebook videos are MUTE after click on PLAY: 
![image](https://user-images.githubusercontent.com/3531623/73182592-9d768700-4119-11ea-982e-51ca005bbf52.png)

(is there also a way to remove the infos at top/left and the share link at top/right?)

**Comment by reganlawton** [comment]
You can now pass through params to the final URL. If the iframe url supports params to remove controls you can now do it. The facebook documentation want be the next best step.
