### ISSUE TITLE
oEmbed requires PHP 7.1.3+

### ISSUE THREAD

**Issue by brandonkelly** [wrav/oembed#33]
Ever since 1.2.0 (067706bdbe5f2e2af879d6834d4951ab419441b1), oEmbed requires `laravel/helpers`, which requires PHP >=7.1.3. That’s a bit of a problem because Craft installs currently require PHP 7.0-compatible dependencies: https://github.com/craftcms/craft/blob/master/composer.json.default#L14-L16

I couldn’t tell from that commit what you’re actually using the `laravel/heplers` package for. If you can show me, I might be able to offer an alternative approach that doesn’t require that package.

**Comment by reganlawton** [comment]
Hmm... @brandonkelly what ever I use it for I can pull it out and replace with vanilla, or use a PHP 7.0-compatible of the helpers library. This shouldn't be an issue at all and happy to fall inline with Craft's support.

**Comment by reganlawton** [comment]
@brandonkelly  can you check `dev-feature/php7` and confirm that it's up to your minium PHP requirements.

**Comment by brandonkelly** [comment]
That appears to have solved it! So I take it you weren’t using anything from laravel/helpers in the first place?

**Comment by reganlawton** [comment]
Original yes I was but I removed the feature that used the helpers and didn’t remove the package in case I needed the helpers, such as collections, etc in future features. I’ll merge this into master and tag a new release.

**Comment by brandonkelly** [comment]
Thanks @reganlawton!
