### ISSUE TITLE
Width and height params do not work

### ISSUE THREAD

**Issue by migswd** [wrav/oembed#35]
I am adding the width and height params to make the iframe bigger but it does not work.
I got oEmbed plugin last version (1.2.4).

Here is my twig code : 
```
{{
entry.resourceLinkEmbed.render({
                params: {
                  width: 1000,
                  height: 500,
                  autoplay: 1,
                  rel: 0,
                  mute: 0,
                  loop: 1,
                  autopause: 1,
                }
              })
}}
```

Et voici le code iframe en output : 

![image](https://user-images.githubusercontent.com/3531623/73956663-90217f80-4905-11ea-93a8-0cac70a80e7a.png)

Thanks for help.

**Comment by reganlawton** [comment]
@migswd firstly thanks for submitting an issue. 

Now the Param field is used to modify the URL query string not the iframe params. However it seems this isn’t the case for you at all. Do you have cache enabled by chance? The width is normally controlled by CSS HOWEVER I can update the DOM manipulation to support updating the width and height attributes.

**Comment by migswd** [comment]
Yes I have cache enabled. I switch it off and I see the url with all params now.
![image](https://user-images.githubusercontent.com/3531623/74009743-2c8a6700-4984-11ea-8d7d-d98f3336bc66.png)

So to modify width and height I should use css or do that : 
`entry.fieldname.render|replace('width="600"','width="100%"')|raw`

That would be great that you update the plugin to take that manipulation in charge yes :)

**Comment by reganlawton** [comment]
@migswd you now have the option to override the width and height, see [v1.2.5](https://github.com/wrav/oembed/releases/tag/1.2.5). I'll also be opening an issue / feature where I'll add support to override / set / manage all iframe DOM. attributes to allow overriding of attributes and adding missing / custom attributes as most my issues are managing attributes 😅

THanks for opening an issue and hope this fixes your edgecase 👍

**Comment by migswd** [comment]
Thats great thank you  !!

Miguel Bocquier
miguel@silkwormdream.com
http://silkwormdream.com
+33 (0) 6 51 40 01 80

**Comment by jdsimcoe** [comment]
Hey @reganlawton previously I had two CSS classes on my iFrame that did formatting with. Now, with `oEmbed` I'm having trouble figuring out how to add these classes via the API. Is there a way to do this?
