### ISSUE TITLE
Detect when video is not available anymore on Youtube?

### ISSUE THREAD

**Issue by migswd** [wrav/oembed#36]
Is it possible to detect (like receive a Craft BO alert) when a video is not available anymore? (cf screengrab)
It happens regularly on Youtube.
![image](https://user-images.githubusercontent.com/3531623/74591375-c6eb4a00-5017-11ea-993b-b3da8530f8c1.png)

**Comment by reganlawton** [comment]
There isn’t really a way to achieve this easily. Does the iframe return a 404 or something? I ask cos if so I could probably, hopefully, just detect a status code and trigger an error.

**Comment by migswd** [comment]
No it is not a 404.
Here the video has become private :
![image](https://user-images.githubusercontent.com/3531623/74629600-e473fd00-5158-11ea-9adf-9ca90bd1513f.png)

**Comment by migswd** [comment]
Awesome !! :)

**Comment by reganlawton** [comment]
Have a new release with opt in setting to get notification via email for broken links. This should be out in the next 12-24hrs. Just have a few things I need to clean up.

**Comment by reganlawton** [comment]
@migswd I have a new feature in settings for the plugin. Try out the v1.3.0 release and let me know. It's still a rough feature but I'll look at options to better it.

**Comment by AdamChlan** [comment]
Hi, I'm curious if this feature is trigged when someone visits the public facing website and private or invalid video is attempted to be loaded...or if it only triggers when someone is working in the control panel, and saves the video URL.
