### ISSUE TITLE
Preview is a bit large

### ISSUE THREAD

**Issue by codyjames** [wrav/oembed#37]
The preview is kinda large (especially on Instagram embeds). I wonder if there is a good way to make the preview be collapsed by default, or something to that effect.

**Comment by reganlawton** [comment]
I quite like this idea TBH 🤔 maybe have a setting to manage it.

**Comment by codyjames** [comment]
That'd be nice. Also, some embeds break out of the width of the container. I'm seeing it currently on Vimeo. I think the Preview stuff just needs some refinement. Not huge deals at all, just some minor issues on a very useful plugin.

**Comment by reganlawton** [comment]
Got a release coming in the next 12-24hrs! Sorry for the delay being quite busy.

**Comment by codyjames** [comment]
Very cool! Thank you, @reganlawton!

**Comment by reganlawton** [comment]
@codyjames Try out the v1.3.0 release and let me know.

**Comment by codyjames** [comment]
It's pretty good! I do have another idea I'm going to try out real quick though (via a fork).

**Comment by reganlawton** [comment]
No issues

**Comment by codyjames** [comment]
I think this can be marked as complete. As either your solution (already implemented) or mine (#40) solve for it.
