### ISSUE TITLE
Render method not working for Instagram

### ISSUE THREAD

**Issue by codyjames** [wrav/oembed#38]
This works fine for Youtube and Twitter, but when I try an Instagram URL, the preview works but the render method does not. I could be doing something wrong but I've done fairly extensive testing.

Ideas?

**Comment by reganlawton** [comment]
Is it any Instagram URL? Can I can a confirmed test link please.

**Comment by codyjames** [comment]
Yeah, I tried multiple URLs. Here is one I tried: https://www.instagram.com/p/B9H26HChL4R/

**Comment by reganlawton** [comment]
Great I’ll look into this when I next get a second. I’m moving this weekend but I might be able to get some time to look into it.

**Comment by reganlawton** [comment]
@codyjames I tested the link you provided `https://www.instagram.com/p/B9H26HChL4R/` and it worked for me. Can you test again to confirm its wasn't an issue with the Instagram server at the time you tested

**Comment by codyjames** [comment]
I'll give it another shot, thanks!

**Comment by reganlawton** [comment]
I'll close just comment here again and I'll reopen if it's still the case. Is you can provide screenshots of what its rendering it'll be helpful.
