### ISSUE TITLE
Works on local but not production

### ISSUE THREAD

**Issue by dbakeernd** [wrav/oembed#41]
Hi! So when I put a YouTube link in my local Homestead/Laravel environment, it works fine. When I push to our production, for whatever reason, it fails. Sometimes it resolves, but it's a little distressing as this is a public website i'm working on. Is there any explanation or solve for this?

Local is nginx. Staging and production is Apache (another company set it up). Don't know if this makes a difference. I keep getting "Please check your URL." I know the URLs are valid.

Please let me know any additional information. It's not the Twig code, so I'm at a loss and can't find any additional documentation that describes this exact issue. Thanks!

**Comment by reganlawton** [comment]
That’s strange. 🤔

Can you try using curl locally via SSH a few times to see if you get rate limited? As the request uses an out bounce request.

Another issue might be caching. Does your site have caching enabled? If so can you try it turned off?

Additional info would be... does this happen every other request or is it always failing no matter what?

Provide your discord info if you want to chat about it.

**Comment by dbakeernd** [comment]
Hi @reganlawton! 

Issue resolved on its own, but when I pushed additional changes it failed. Ran a curl request and it succeeded. Ran a few more for safety and they all went through.

Caching is not enabled; cleared caches just in case, but no luck.

**Comment by reganlawton** [comment]
@dbakeernd sorry so your still having issues?

**Comment by reganlawton** [comment]
@dbakeernd I'm closing but if the problem continues plus comment and I'll reopen.

**Comment by lenvanessen** [comment]
@reganlawton 
Its probablby due to https://github.com/oscarotero/Embed/issues/337
Should work in version 4.0 of Embed, as the api's are mostly not ratelimited but the sites are.

**Comment by jdsimcoe** [comment]
@lenvanessen I'm assuming `oEmbed` would have to be upgraded to support `embed` 4.x? I'm encountering this same issue right now:

https://github.com/wrav/oembed/issues/50

**Comment by reganlawton** [comment]
The v4 changes have been ported over to v3 branch from my knowledge you can use composer update to get the latest v3 changes on embed/embed
