### ISSUE TITLE
Description character count limited?

### ISSUE THREAD

**Issue by danvolkens** [wrav/oembed#42]
It seems that description is char-limited to 246 or so. Is that intentional? If it is, we'll make sure to adjust our descriptions to accommodate. Here's an example: https://oscarotero.com/embed/demo/index.php?url=https%3A%2F%2Fwww.buzzsprout.com%2F108830%2F2249300-ventilation-oxygenation-and-perfusion

Tks!

**Comment by reganlawton** [comment]
THis is a good point. I only used a input field, which would be a VARCHAR by default, so I'll have to look at converting to a TEXT column. 

This is doable.

**Comment by danvolkens** [comment]
Thanks, man! I'll pass along there as well.

**Comment by danvolkens** [comment]
Just to wrap this up and put it to bed, here is the owner's response, which makes sense! Tks again for looking into it. We'll just accommodate on our side.

https://github.com/oscarotero/Embed/issues/353
