### ISSUE TITLE
Instagram not working on production

### ISSUE THREAD

**Issue by bradhardinge** [wrav/oembed#44]
Hi there, I've been able to get Facebook and Instagram links working great locally. Just pushed an update to test live and Facebook works fine by Instagram does not. See screenshots below. Any ideas?

Local:
![Screen Shot 2020-05-25 at 3 20 24 pm](https://user-images.githubusercontent.com/2033525/82780735-6cc21680-9e9b-11ea-8b7c-e9a77b4a301c.png)

Live:
![Screen Shot 2020-05-25 at 3 19 25 pm](https://user-images.githubusercontent.com/2033525/82780771-819eaa00-9e9b-11ea-9e64-70b367a36cb8.png)

**Comment by reganlawton** [comment]
@bradhardinge 

Does it work on production with the query string? 
Do you have caching enabled?
Can you please also provide the URL here please.

**Comment by bradhardinge** [comment]
@reganlawton 

Sorry no, I took the screenshots at different times but I tried with and without the querystring and with a number of different links.

Cache is turned off in the oEmbed plugin settings.

Here is a Instagram URL I just tested, same issue: https://www.instagram.com/p/CAY_UEQlhf6/

Get the following issues in devtools: 
![Screen Shot 2020-05-25 at 5 07 32 pm](https://user-images.githubusercontent.com/2033525/82788051-0f35c600-9eab-11ea-984b-a0f4f43f3c36.png)

**Comment by reganlawton** [comment]
OH! It looks like you have SameOrigin headers set. This isn't a issue with the plugin more the server. You can read more about it and Content-Security-Policy (CSP) here (https://www.geeksforgeeks.org/http-headers-x-frame-options/). YOu;ll need to modify your Apache / Nginx configure here.

This raises a massive point those that I need to have in the README something about Cross Site SecOps side of the plugin.

**Comment by bradhardinge** [comment]
@reganlawton 

Oh right, I'll see if I can work out the server config stuff.

Odd this effects Instagram but not Facebook.

**Comment by reganlawton** [comment]
Hmm actually now I see that error closer. it might be instagram server that’s got the policy 🤔 I’ll have to spin up a box in the AM and look at that link closer

**Comment by bradhardinge** [comment]
@reganlawton 

I think you're right about it being Instagram limiting what we can use with embed. I was trying to use the the following in my own design:

```
{{ entry.field.media.url }}
{{ entry.field.media.title }}
{{ entry.field.media.description }}
{{ entry.field.media.image }}
```

Looks like this is specifically not allowed (see here: https://developers.facebook.com/docs/instagram/embedding)

> ...Using metadata and media content (or their derivations) from the APIs for any purpose other than providing a front-end view of the media content is strictly prohibited. This prohibition encompasses consuming, manipulating, extracting, or persisting the metadata and media content, including but not limited to deriving information about posts from the metadata for analytics purposes.

Using an Instagram URL in the following format `https://www.instagram.com/p/CAY_UEQlhf6/embed` works with `entry.field.render`

**Comment by reganlawton** [comment]
@bradhardinge Great find! 

They must have a new policy as last time used instagram it worked. I'm not a massive Instagram user myself, mostly to watch skateboard related content, so I must have missed this. I'll have to pin this issue in the README as this is "need to know".

I got abit crazy this morning and only just got to this now.
