### ISSUE TITLE
Get the width and height attribute from a direct vimeo link

### ISSUE THREAD

**Issue by helleholmsen** [wrav/oembed#45]
How can I get the width and height from a direct vimeo url? The plugin fetches and returns the url but the media.width and media.height returns null. If the plugin doesn't do that, is it possible to get the preview image from the CP?

**Comment by reganlawton** [comment]
What’s the URL your trying to URL? So I’m unable to test. I believe it should be working

**Comment by helleholmsen** [comment]
@reganlawton https://vod-progressive.akamaized.net/exp=1590761946~acl=%2A%2F1832751525.mp4%2A~hmac=af3d6bc73d964b280ca2ba77b962fb8ca343d977d7317c562e0d0719bd4becca/vimeo-prod-skyfire-std-us/01/4716/16/423581061/1832751525.mp4

**Comment by reganlawton** [comment]
I’ll take a look over the weekend.

**Comment by reganlawton** [comment]
The URL you provided isn't going to work firstly as it's giving a error "Access Denied". Secondly your URL is a direct MP4 file not a vimeo link, a vimeo link looking like so.

```https://vimeo.com/1084537```

Can you try using the vimeo URL not the direct vimeo video URL.

**Comment by helleholmsen** [comment]
@reganlawton yes, I'm aware that it works with the vimeo embed but what if you just want to use the video as a background video to loop without the player?

**Comment by reganlawton** [comment]
This plugin takes a link and returns a iframe based on the OEmbed protocol. If you want to use a MP4  video file just use the built in HTML <video> element. There is no need for a plugin.

I’m I correct that your wanting to use a MP4 file link?

**Comment by helleholmsen** [comment]
@reganlawton you are correct :) The vimeo URLs are being posted in the CMS so I was trying to test if the plugin could get the height, width or thumbnail so I could get the aspect ratio before the video was loaded.

**Comment by reganlawton** [comment]
Argh yep I see. This plugin can’t get that meta data as it requires the oembed meta data. By accessing a file directly there’s nothing to act on.

Sorry the plugin wasn’t able to meet your needs 😅

**Comment by helleholmsen** [comment]
@reganlawton ok! thank you for replying :)
