### ISSUE TITLE
Preview Doesn't Appear Until Entry Saved

### ISSUE THREAD

**Issue by mattrothenberg** [wrav/oembed#5]
Howdy! Thanks for building this fantastic plugin.

I'm not sure whether this is a bug, feature request, or something altogether different.

When pasting a URL into an `oEmbed` field, I expect something to appear in the **Preview** field directly underneath. However, I can't get anything to appear until I've saved the entry and the page refreshes.

Is this intentional? It would be helpful for content creators on my site to be able preview their embed link, just to verify that they're pasting something that actually works.

❤️

**Comment by reganlawton** [comment]
@mattrothenberg I'll look into this as it should work without the the entry needing to be saved

**Comment by reganlawton** [comment]
@mattrothenberg I've tested a fix that is caused when using a Matrix or another dynamic type I'll have a patch out for you in a minute

**Comment by reganlawton** [comment]
Resolved in [v1.0.5](https://github.com/wrav/oembed/tree/1.0.5)

**Comment by mattrothenberg** [comment]
@reganlawton Amazing. Thank you so much!
