### ISSUE TITLE
Add support for title attribute

### ISSUE THREAD

**Issue by tomkiss** [wrav/oembed#51]
To improve accessibility for screen readers, it's desirable to have a `title` attribute on the rendered iframe.

Is there any chance support for this could be added? :)

Thanks 🙏

**Comment by reganlawton** [comment]
How would this work? are we talking url or site title? I'm happy to look into is I can get some guideline around the end goal. Maybe show an example or your exxpected output and I can look into getting it in

**Comment by tomkiss** [comment]
Sure thing @reganlawton ,

Here's an article on frames having title attributes:
https://dequeuniversity.com/rules/axe/4.0/frame-title?application=msftAI

For implementation, it would ideally be a simple options parameter, something like this:

```
{{ craft.oembed.render(entry.embedField, {
    title: "2020 Product X Announcement Trailer",
    params: {
        autoplay: 0,
    }
}) }}
```

Which could result in something like this:

```
<iframe title="2020 Product X Announcement Trailer" width="480" height="270" src="https://www.youtube.com/embed/XYZ123" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

**Comment by reganlawton** [comment]
Have you tried adding the title to the params options? I'd need to rest but I'm pretty sure that might work.

**Comment by tomkiss** [comment]
> Have you tried adding the title to the params options? I'd need to rest but I'm pretty sure that might work.

Sorry, no that does not work.

**Comment by reganlawton** [comment]
Give v1.3.6 a shot with the new attribute options.

**Comment by tomkiss** [comment]
Hi there, thank you, this is great! Thanks so much for implementing. Do you have a beer buying button anywhere? 😃

Unfortunately, initially, I thought it wasn't working, but it appears I had an existing bug related to usage in matrix fields (sorry!), which I've [reported here](https://github.com/wrav/oembed/issues/61).

**Comment by reganlawton** [comment]
Was simple fix I've just been insanely busy so thank you for sticking in there 😅￼
