### ISSUE TITLE
CP resources for oEmbed plugin are added after HTML end tag

### ISSUE THREAD

**Issue by bencomp** [wrav/oembed#52]
I just installed the oEmbed plugin (v1.3.4 on Craft 3.5.5) and added a oEmbed field to an entry type. When editing an entry, I noticed that the control panel resources, i.e. the JavaScript and CSS, are outside the HTML document:

```html
...
</body>
</html>
<script src='https://paleo.test/cpresources/14d5b05b/oembed.js?v=1598262036'></script><link rel='stylesheet' href='https://paleo.test/cpresources/3ebdc379/oembed.css?v=1598262036'>
```

I am not sure if this is a bug in the plugin; I haven't looked that far into the code. The first oEmbed item I tried to load (<https://purl.stanford.edu/fw090jw3474>) would not show and wanted to look at the browser's network monitor panel to find out why, which is when I noticed the issue above.

**Comment by reganlawton** [comment]
This might be an issue with the JS loader I’m happy to take a PR if you solve the issues but I’m currently out of action till minimum the weekend due to Retinal Detachment surgery on my eye and limited to a particular head position for the next week

**Comment by bencomp** [comment]
Hi @reganlawton, thanks for the quick response. I'm pretty new to Craft, oEmbed and the plugin system, so I wouldn't know where to start. I'm not even sure how much this affects working with the plugin. So I can wait and return to the issue later.

I hope your surgery and recovery go well!

**Comment by reganlawton** [comment]
I'm back at the computer I'll look into this to fix but in the short time  this shouldn't be a major issue as modern broswers should figure it out but a fix should be added.
