### ISSUE TITLE
Embed Instagram with params `hidecaption` didnt work

### ISSUE THREAD

**Issue by hongc-cc** [wrav/oembed#54]
The instagram `hidecaption` params didnt work
`{{ block.embed.render({ parms:{ hidecaption: true } })  }}`

Temporary fix:
`{{ block.embed.render() | replace({'data-instgrm-captioned': ''}) | raw }}`

any idea on why it isnt working?

**Comment by reganlawton** [comment]
I'll have to look into this

**Comment by chanwhab** [comment]
Any update?

seems like ` {{ block.embed.render() | replace({'data-instgrm-captioned': ''}) | raw }}` is not working great as it cause strange spacing in mobile safari.

**Comment by reganlawton** [comment]
It should be `{{ block.embed.render({ params:{ hidecaption: true } }) }}` it seems you had a typo unless that was only on Github.
