### ISSUE TITLE
Instagram Endpoint changing on 24Oct - What's the influence

### ISSUE THREAD

**Issue by chanwhab** [wrav/oembed#55]
As instagram is sunsetting the old endpoint API in 24 Oct.
Is there any plan to migrate to new endpoint?
https://developers.facebook.com/docs/instagram/oembed#oembed
https://oembed.com/
see instagram section

**Comment by reganlawton** [comment]
This will be something handled in the underlying embed/embed package we use.

**Comment by chanwhab** [comment]
yes thanks. Just want to make sure this is taken care of. 
It might be affecting lots of users

**Comment by reganlawton** [comment]
Agreed I'll have to test this out and check the package

**Comment by reganlawton** [comment]
@chanwhab I believe this is all working still?
