### ISSUE TITLE
Searching for oembed fields that contain a URL

### ISSUE THREAD

**Issue by arentsen** [wrav/oembed#58]
I would like to make a query in Craft CMS for oembed fields that contain a link and skip entries that don't. It does 

I tried to add this to my query:

{% set videoNews = craft.entries
    .section('news')
    **.search('videoEmbed.media.url:*')**
    .orderBy('postDate desc')
    .one() %}

Even adding **.search('videoEmbed:*')** does not work. How to find embedded fields that are not empty?

**Comment by iparr** [comment]
Untested, but have you tried `:notempty:` to search fields? - ala [this example.](https://craftcms.stackexchange.com/questions/452/return-entries-where-field-is-not-empty) 

This is inefficient in most scenarios, but does the trick.

**Comment by reganlawton** [comment]
I think @iparr is right as the field doesn't allow for querying as such. I think I might need to look at the storage method of the field abit as it storing JSON as TEXT, mostly cos of legacy, but I might be able to get the field to support JSON field type and then let us have the querying power.

**Comment by arentsen** [comment]
Thanks, it does the trickMet vriendelijke groet,With kind regards,Matthias Arentsen27.09.2020, 18:18, "Ian" <notifications@github.com>:
Untested, but have you tried :notempty: to search fields? - ala this example.
This is inefficient in most scenarios, but does the trick.
