### ISSUE TITLE
Is it possible to get a higher quality version of the image?

### ISSUE THREAD

**Issue by helleholmsen** [wrav/oembed#59]
{{ entry.oembed.media.image }} always gives me a small version of the image I'm trying to fetch - example: https://i.vimeocdn.com/video/938592587_295x166.jpg

I'm guessing this is because when I dump the element from vimeo the dimensions are always small, for example:
"width": 426
"height": 240

Is it possible to set the width and height to be hq before the element is rendered?

**Comment by reganlawton** [comment]
@helleholmsen this should be followed up on the embed/embed package as that data comes from there. Im afraid I cant do anything here.

**Comment by helleholmsen** [comment]
@reganlawton ok :)

**Comment by brycekirk** [comment]
To save someone else the time it takes to follow the rabbit hole, here's the issue in question: https://github.com/php-embed/Embed/issues/391

The solution recommended there does work. So you would do something like this in your template:
```
{% set img = class.oEmbed.media.image %}
{% set img = img|split('_')[0] ~ '_1280x720' %} {# Split the image URL before the size designation, which always starts with an underscore, and add your own custom size #}
```

Kinda sketch, but it works.
