### ISSUE TITLE
Preview failing for Libsyn oEmbed link

### ISSUE THREAD

**Issue by rtgoodwin** [wrav/oembed#6]
Hi!

The perfect plugin to help me move some of my entry content out into a proper field structure. :) I was going to use Libsyn's iframe, but oEmbed seems like a more sane, structured option to use if I can. 

I installed the plugin, added a field, and tried entering the URL, but the Preview fails, saying "check your URL". I'm wondering if there's a bug, or  Libsyn isn't doing its oEmbed _thing_ right. 

Here's the URL in question: `https://oembed.libsyn.com/embed?item_id=8634992`. I can drop it into a browser fine, and `wget` it. I even tried copying out the (ahem) embedded oEmbed link inside the payload and that didn't work either: `https://oembed.libsyn.com?item_id=8634992`. (I validated that the second link does return a JSON payload.) 

I haven't yet tried to render the field, but I figure this is a bug either way even if it's just the preview. 

Any ideas? Thanks for making this! 

System info:
```
PHP version | 7.2.15
Linux 4.15.0-43-generic
MySQL 5.7.25
Imagick 3.4.3RC2 (ImageMagick 6.9.7-4)
Craft Solo 3.1.14
oEmbed 1.0.5
```

**Comment by reganlawton** [comment]
@rtgoodwin I've tested those URLs with other services and they don't seem to support the Oembed format. See example tester [here](http://oembed.frdnspnzr.de/).

You might want to contact the `libsyn` service and ask them. But it does seem to follow [spec](https://oembed.com/) at first glance.

I'll need to look into this more.

**Comment by rtgoodwin** [comment]
@reganlawton Thanks! The JSON (at least the direct URL) does seem to be valid, from what I could glean from a quick read of the spec. 

Embed.ly's tester reports it's valid, but I think Libsyn probably designed it with them in mind :) 

Thanks for any help or ideas. I'll bug them as well.

**Comment by rtgoodwin** [comment]
@reganlawton 

Libsyn responded that it should be following the spec, and:

```Most of the 'testers' out there seem to be looking for the metatags for discovery:  https://oembed.com/#section4 and not actually parsing the response.```

I patched the local Essence install and created a PR: https://github.com/essence/essence/pull/144 and it works fine now. (Forces Essence to match Libsyn as a "special" provider since it's not matching it as a generic oEmbed provider.) 

Hoping to figure out the root cause though, in case Essence doesn't get updated, and/or to help others out. :)

**Comment by reganlawton** [comment]
@rtgoodwin

I’ll create a new brwnch so that your able to reference that in composer, say something like ‘dev/libsys ‘ etc.

That’ll reference the essence PR this should be a fix till your PR gets pulled into core.

**Comment by reganlawton** [comment]
@rtgoodwin 

Please let me know when your [PR](https://github.com/essence/essence/pull/144) has been merged  into master. I have a new branch `dev-hotfix/libsyn` that you can reference in your composer.json in your CraftCMS project, this has your PR set and is locked to that initial PR commit.

Like me know if thats good your end and thanks for the report 👍

**Comment by rtgoodwin** [comment]
Awesome! Will let you know; the other PR in there has been hanging out for quite some time, but hopefully this one goes quickly. Thank you so much!

**Comment by rtgoodwin** [comment]
I can't seem to tag you across repos (or tell if you get updates on that PR), but Felix posted a couple of updates, so just letting you know here :) https://github.com/essence/essence/pull/144

**Comment by reganlawton** [comment]
@rtgoodwin thanks for that once the repo owner makes the final changes I'll do a big update here

**Comment by rtgoodwin** [comment]
@reganlawton Do you think you'll add the default providers in the Essence instantiation as Felix mentioned? I think that way I can unpin a specific version here. Not trying to be redundant posting, just not clear on if you get notified on that thread. :) I'm not sure if I can test it out in my current config but I could pin to a different commit on your side if you wanted to push a test version.  Thanks on this! 

Just for additional fun I learned that the oEmbed version of their player (not the regular iframe) they fix to a 600 width, which is also kind of annoying in scenarios like mobile where it doesn't degrade gracefully. Your plugin and Twig to the rescue: 

`entry.podcastPlayerEmbed.render|replace('width="600"','width="100%"')|raw`

(Unless there's some way to force it into a container to override its width but I suspect that could end up wonky. Anyway, just trivia, not your issue :) )

**Comment by reganlawton** [comment]
@rtgoodwin I've changes the package used and its now fix in v1.1.0

**Comment by rtgoodwin** [comment]
@reganlawton Well thanks! Didn't mean to cause such a ruckus :)

**Comment by reganlawton** [comment]
@rtgoodwin all good i found a few more sites that that package couldn't handle yet so it was better to switch over the dependency. Thanks for the report 👍
