### ISSUE TITLE
Relevant YouTube URL parameters are ignored

### ISSUE THREAD

**Issue by tomkiss** [wrav/oembed#61]
[original issue rephrased]

When pasting in YouTube URL parameters, some are ignored and do not make their way to the embedded video markup.

**Comment by reganlawton** [comment]
SIlly question but do you have caching on? As it should work the exact same if so I think there might be an issue with the cache busting with the new attribute feature

**Comment by tomkiss** [comment]
I'm pretty sure it's not caching - I've flushed the craft caches multiple times before posting, but this was also in devmode locally.

This this bug may predate the attributes functionality as I couldn't see the params rendering before with the matrix field usage.

**Comment by reganlawton** [comment]
It should be in the settings but is there any additional Dump die type data you can do to help troubleshoot? It's abit strange as I've never seen this type of issue and it's running through the code so can you check if the code it right when the service returns it to the matrix? Trying to see if you have something stripping it afterwards.

**Comment by tomkiss** [comment]
Hmmm, ok.

I'll test again later on a free craft install and report back.

**Comment by reganlawton** [comment]
Yeah any additional information including plugins and such will greatly help and even dump and inside the plugin service to see that its setting the changes that way you can see where its failing and then I'll be able to update it much easier.

**Comment by tomkiss** [comment]
Ok, I've done a bit of tinkering now, and found the problem!
It occurs when the (YouTube) URL has existing query strings in and it occurs across all videos (not just matrix fields as originally thought).

**Test template:**

```
{{ craft.oembed.render(globalVars.embeddedMedia, {
    params: {
      autoplay: 1,
    },
    attributes: {
      title: block.media.media.title | default('Embedded media'),
    },
  }
) }}
```

**Test 1: URL with no query strings:**

_Input URL:_
`https://www.youtube.com/watch?v=9WfZuNceFDM`

_Output:_
`<iframe width="480" height="270" src="https://www.youtube.com/embed/9WfZuNceFDM?autoplay=1&amp;feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="" title="Embedded media"></iframe>`

**Test 2: URL with query strings:**

_Input URL:_
`https://www.youtube.com/watch?v=9WfZuNceFDM&t=20s`

_Output:_
`<iframe width="480" height="270" src="https://www.youtube.com/embed/9WfZuNceFDM?start=2&feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

I think this threw me because the difference is hard to tell. The video still renders and so it's perhaps not noticeable unless there are some critical options or attributes being set.

So, I guess there are two bugs here. First, is that the options/attributes are not set. And second is that it converts `t` to `start`, which for YouTube at least, I don't think is valid. On YouTube, the "t" parameter is quite handy and there is a UI on the YouTube embed side to help generate it, so it's helpful for editors adding the videos in.
Perhaps it could respect any existing, but non-conflicting params? I guess you could whitelist them in order to determine valid ones but this would be a point of maintenance.

**Comment by reganlawton** [comment]
@tomkiss is this still the issue in the newer versions?

**Comment by tomkiss** [comment]
Hi @reganlawton - OK so I've checked it all out and it seems to be... fine!

The `t` / `start` issue is somewhat confusing. `start` is used by the YouTube API, which is presumably what the Oembed format adheres to. But YouTube uses `t` when generating the [short] URLs (presumably for brevity).

Anyway, all seems to be working fine at the moment 😀

**Comment by tomkiss** [comment]
OK, @reganlawton.

Apologies, I had to delete my previous reply because it's still morning and I hadn't quite gotten my head back into the original problem. Yes the problem still exists, although I'm not sure if its bug or feature request.

**Test 3**

**Template:**

```
{{ craft.oembed.render('https://www.youtube.com/watch?v=9WfZuNceFDM&t=30s&autoplay=1&controls=0', {
    attributes: {
      title: block.media.media.title | default('Embedded media'),
    },
  }
) }}
```

**Output:**

```
<iframe width="200" height="113" src="https://www.youtube.com/embed/9WfZuNceFDM?start=30&feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

**Expected output:**

```
<iframe width="200" height="113" src="https://www.youtube.com/embed/9WfZuNceFDM?start=30&autoplay=1&controls=0&feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

Although `controls` and `autoplay` can be successfully set in the template, because it ignores them in the URL, there's no way for editors in the CP to apply them on a per-video basis.

So, my suggested improvement here would be to honour the values in the URL, if they exist. e.g:

When a template is as such:

```
{{ craft.oembed.render(globals.videoURL, {
    params: {
      autoplay: 1,
    },
    attributes: {
      title: block.media.media.title | default('Embedded media'),
    },
  }
) }}
```

When `globals.videoURL` is set to `https://www.youtube.com/watch?v=9WfZuNceFDM&controls=0` then the output should be `https://www.youtube.com/watch?v=9WfZuNceFDM&autoplay=1&controls=0`. 
Presently, the `controls` URL param would not be set. 

But when `globals.videoURL` is set to `https://www.youtube.com/watch?v=9WfZuNceFDM&autoplay=0` then the output should be `https://www.youtube.com/watch?v=9WfZuNceFDM&autoplay=0`. 
Presently, the URL param of `autoplay` is ignored and only the template value used.

Does that make sense? I'll update the title of the issue.

**Comment by reganlawton** [comment]
@tomkiss I'll look into this and get some testing time sloted

**Comment by reganlawton** [comment]
Is this resolved in the new versions?

**Comment by tomkiss** [comment]
Thanks @reganlawton. No nothing seems to have changed.

Here's my test for your reference:

### Test 1: Does valid YouTube URL param get set?

In this example, the [YouTube URL parameters](https://developers.google.com/youtube/player_parameters) for `autoplay` and `controls` are set in the URL.

```
{{ craft.oembed.render('https://www.youtube.com/watch?v=9WfZuNceFDM&controls=0&autoplay=1', {
    attributes: {
      title: 'Embedded media',
    },
  }
) }}
```

#### Output:

Both of the parameters are ignored in the output:

 - Rendered URL: `https://www.youtube.com/embed/9WfZuNceFDM?feature=oembed`
 - Expected URL: `https://www.youtube.com/embed/9WfZuNceFDM?feature=oembed&controls=0&autoplay=1`

```<iframe width="200" height="113" src="https://www.youtube.com/embed/9WfZuNceFDM?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="" title="Embedded media"></iframe>```


### Test 2: Does URL param override template param?

In this example, the `autoplay` and `controls` are again set in the URL, only this time the template defines them too.

```
{{ craft.oembed.render('https://www.youtube.com/watch?v=9WfZuNceFDM&controls=0&autoplay=1', {
    params: {
      controls: 1,
      autoplay: 0,
    },
    attributes: {
      title: 'Embedded media',
    },
  }
) }}
```

#### Output:

The parameters are set, but with the values from the template.

 - Rendered URL: `https://www.youtube.com/embed/9WfZuNceFDM?autoplay=0&controls=1&feature=oembed`
 - Expected URL: `https://www.youtube.com/embed/9WfZuNceFDM?autoplay=1&controls=0&feature=oembed`

```<iframe width="200" height="113" src="https://www.youtube.com/embed/9WfZuNceFDM?autoplay=0&amp;controls=1&amp;feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="" title="Embedded media"></iframe>```

**Comment by reganlawton** [comment]
Hmm thats weird let me look some more

**Comment by reganlawton** [comment]
@tomkiss That seems to be working? That's weird...

<img width="1211" alt="Screen Shot 2021-07-22 at 10 41 39 am" src="https://user-images.githubusercontent.com/2705875/126576631-a4574949-d943-49e9-8bbe-f240c87c2ac3.png">

**Comment by tomkiss** [comment]
If you notice, the 'autoplay' and 'controls' URL params are not set in the iframe 'src' attribute.

(They are stripped out, despite being supported by YouTube).

Ideally, the plug-in would:
 1. Parse URL params against those supported (I linked to the documentation in my previous post)
 2. Remove out any that are not supported
 3. Apply any params defined at the template level and any resolve conflicts (eg if 'autoplay' is defined in both URL and as template variable, maybe override template with the url one)
 4. Render video!

If these are then supported, features such as 'autoplay' and 'controls' could then be defined by editors in the CP. With no need for any UI, in line with YouTube API, mega win.

**Comment by reganlawton** [comment]
I used in my iamge above:

```twig
{{ 
    craft.oembed.render(
        'https://www.youtube.com/watch?v=9WfZuNceFDM&controls=0&autoplay=1',
        {
            attributes: {
                title: 'Embedded media',
            },
        }
    ) 
}}
```
=================================================================

<img width="1208" alt="Screen Shot 2021-07-22 at 8 13 27 pm" src="https://user-images.githubusercontent.com/2705875/126623761-47ddbcf6-7dd5-45d0-9128-e9742b055a17.png">

and the image now shows:

```twig
{{
    craft.oembed.render(
        'https://www.youtube.com/watch?v=9WfZuNceFDM&controls=0&autoplay=1',
        {
            attributes: {
                title: 'Embedded media',
            },
            params: {
                autoplay: 0,
                rel: 0,
                mute: 0,
                loop: 0,
                autopause: 0,
            }
        }
    )
}}
```

This is all working as it should.

**Comment by tomkiss** [comment]
> 
> This is all working as it should.
> 

Hey there,

Sorry. This is MONTHS later, isn't it?

So, in your example there, the original URL has `&autoplay=1`

But in the outputted URL, this has been removed, and it displays `&autoplay=0`.

However, in your example the template is "overriding" the query string parameter, which is a more subjective (Test 2 above).
So the more clear example is the fail in **Test 1** above.

If it didn't remove the query strings, then it would allow editors a small degree of control.
