### ISSUE TITLE
Preview doesn't work everywhere

### ISSUE THREAD

**Issue by lukasgeiter** [wrav/oembed#62]
Thanks for your work! I'm running into an issue with the preview of embedded content...

The JavaScript and CSS responsible for the preview is only loaded on entry pages. However, due to how fields work in Craft the field can show up in various other places - such as assets, globals, categories, dashboard widgets etc.

Why did you change it so the resources are only loaded for pages under `/admin/entries/`? (commit 6cb0912767574ade59b5d484605c347b7b413c7a)  
And would you be willing to revert this change so the preview works across the whole control panel?

**Comment by reganlawton** [comment]
This was changed due to an issue with JS errors on frontend for some users if the jquery wasn't used. I think two parts need to happen here. I think I need to refactor the jQuery out and secondly open the regex to additional areas of the admin panel

**Comment by lukasgeiter** [comment]
That doesn't really make sense though because the `getIsCpRequest()` check already excludes the frontend. I dug through the old issues and found issue #12 which seems to be the motivation for the regex.

The original problem is about the `<script>` tag being included in a JSON result. Only including assets in certain control panel areas isn't really the best fix for that. The assets should be included in all full page HTML results - or ideally only when the field itself is rendered as well.

Fortunately this is actually pretty easy to do. I've created a PR (#63) that should solve this issue along with #52.
