### ISSUE TITLE
Not able to change Soundcloud embed size 

### ISSUE THREAD

**Issue by arentsen** [wrav/oembed#66]
How can I embed a smaller Soundcloud iframe? I tried in Craft CMS

```
artistAudio.audioUrl.render( {attributes: { height: 300 } } )
```
but it does not change the size of the widget. Soundcloud says it has different sizes for embedding and 300 is the smallest, I but prefer even a smaller iframe than 300.

Any input would really be appreciated

**Comment by reganlawton** [comment]
It might be Soundcloud that's need's to have it passed via `params` option. I believe I made it so it so `attributes` didn't override existing attributes to stop this like changing the url and such.

**Comment by arentsen** [comment]
both the params and attributes do not work. Even forcing CCS does not seem to work since the widget is rendered and overwrites everything.

**Comment by reganlawton** [comment]
@arentsen are you able to see the latest versions?

**Comment by arentsen** [comment]
Nothing gets rendered when I use any attributes or parameters so I just leave them empty for now. I don't have much time currently to do more testing. Thanks though for mentioning. This is how I discovered there was an update to the plugin. It seems some other things have changed since I had to change field.media.url to field.url everywhere in my templates :-) For the rest, everything works fine so very happy with your plugin!

The one downside to this plugin is that if someone enters a false link, Craft returns a internal server failure that breaks up the site. I cannot use any usual method (default or length) to check if the link is valid, because even using .valid returns the same internal server error (on the front end if someone is not logged in). It does not show on the backend always that the site will break up with the current link :-)

**Comment by reganlawton** [comment]
yeah I'm looking into ways to fix the 500 errors on broken URL's and I think there's an issue with the `attributes` param so I'll look into that more.

**Comment by arentsen** [comment]
That would be great! There is another thing that is happening after the plugin update. When the Oembed field is not filled in, it still shows the message "Please check your URL." underneath the preview. This causes the query .field(':notempty:') to not work because it still finds the fields that are empty but show this message. It happens with all newly created entries it seems. Thanks!
