### ISSUE TITLE
How to use options?

### ISSUE THREAD

**Issue by CreateSean** [wrav/oembed#7]
I have this working with YouTube, however the youtube embed is automatically setting the height and width attributes in the iframe tag. I'd like to be able to set those myself.

My current code is:

```
{% set options = {
  height: "405px",
  width: "720px"  
} %}

{{ craft.oembed.render(block.youtubeLink, options) }}
```

However the options don't appear to be doing anything.

**Comment by reganlawton** [comment]
@CreateSean The passed into [Essence](https://github.com/essence/essence) are used as query parameters for the oembed spec,  [see "2.2. Consumer Request"](https://oembed.com/#section2).

I'd need to test to confirm but Im pretty sure maxwidth / maxheight can be used in youtube case. However @rtgoodwin in issue #6 put forward the solution below.

```twig
entry.fieldname.render|replace('width="600"','width="100%"')|raw
```

**Comment by reganlawton** [comment]
@CreateSean Just tested and can confirm that maxwidth and maxheight works
