### ISSUE TITLE
Support GraphQL fragment by registering an interface

### ISSUE THREAD

**Issue by joshuabaker** [wrav/oembed#70]
At present, it doesn’t appear possible to share fields via a GraphQL interface fragment (like `OembedInterface` below). Would this be a challenge/breaking change to support?

```gql
fragment embed on OembedInterface {
  title
  description
  url
  type
  image
  imageWidth
  imageHeight
  code
  width
  height
  aspectRatio
  authorName
  authorUrl
  providerName
  providerUrl
}
```

**Comment by reganlawton** [comment]
@joshuabaker I would have to look into the change as the GraphQL support was added original as a nice to have and being a free plugin I didn't want to assign insane amount of effort too it so there is plenty of growth in the GraphQL feature.

**Comment by joshuabaker** [comment]
Thanks, @reganlawton. Totally understand! Really appreciate that there’s support as is.

**Comment by joshuabaker** [comment]
Stale issue, so I’m going to close.
