### ISSUE TITLE
When embedding a pinterest URL the language of the pinterest interface is in Spanish

### ISSUE THREAD

**Issue by EstherDevs** [wrav/oembed#72]
When I embed a pinterest link like this one for example: 
https://nl.pinterest.com/pin/828732768903490501/

The interface button from pinterest and the "this pin is from" text displays in Spanish rather than Dutch. 
My craft, computer and the URL are all set to use Dutch language so it's unclear to me why it displays this way. 

I've attached a screenshot of the output on my page when using the above example URL

![Screenshot 2021-04-16 at 09 56 45](https://user-images.githubusercontent.com/14767809/114991864-5e596080-9e9a-11eb-9469-a68d616ae231.png)

**Comment by reganlawton** [comment]
I believe this is an issue with the pinterest oembed handling. This isn't much I can handle here unless the core package `embed/embed` does something.
