### ISSUE TITLE
When caching is enabled, YouTube embeds do not include additional parameters in the returned iFrame

### ISSUE THREAD

**Issue by bendesilva** [wrav/oembed#73]
Untested on other providers, however it appears that when I have caching enabled, the iFrame does not include any of the additional parameters defined in templates (for context I'm trying to add the `enablejsapi` parameter). I tried flushing and clearing all caches, creating a new entry with a video that had not been embedded on the website before and in all instances the embed didn't include the parameter in the iFrame src. When disabling the cache the parameter appeared as expected.

I did try disabling the cache for an extended time but was quickly rate limited by YouTube.

oEmbed version: 1.3.6
Craft CMS version: 3.6.11.2

**Comment by reganlawton** [comment]
@bendesilva sorry for the delay been out due to health issues. I can confirm that the URL is the only key the cache uses and I'll have to hash the options to get this fixed.

**Comment by reganlawton** [comment]
You should be able to see the changes on v1.3.8

**Comment by bendesilva** [comment]
Thanks @reganlawton, no need to apologise, thanks so much for this fix! Really appreciate your help.
