### ISSUE TITLE
After upgrade, nothing is saving or displaying properly

### ISSUE THREAD

**Issue by adrienne** [wrav/oembed#79]
Videos show in the control panel:
![image](https://user-images.githubusercontent.com/89705/122253278-dfc07580-ce80-11eb-8c1f-42c386b4c281.png)

 but on the front end i get an error if I try to render anything to do with the oEmbed field: 
 `Key "media" does not exist as the array is empty.`

And the database doesn't seem to be saving anything except the actual URL anymore? (Formerly it would save JSON like:
`{"url":"www.youtube.com/watch?v=oaCOAP465Eg","oembed":null}` )

We haven't changed ANYTHING except upgrading Craft and oEmbed, and suddenly half the pages on our site aren't working -- please help!

**Comment by adrienne** [comment]
Just tagging @reganlawton to make sure eyes get on this asap!

**Comment by reganlawton** [comment]
@adrienne whats the `content` column showing? It was working for me on my testing for the multiple level bug. I'm just wondering if I missed anything.

**Comment by adrienne** [comment]
I've got caching turned on and the column is showing just this:
`{"url":"https://www.youtube.com/watch?v=vAEHeJof1vI"}`

Still getting the error, and when i try dumping from Twig like this:
`{{ dump(entry.videoEmbed) }}`
it shows me 
`array(0) { }`
so it's just … not getting any content somehow? 

I can try a few other tests. It seems to be happening with every provider, so it's not something easy like being rate-limited.

The field is inside a Matrix, but i don't _think_ that should make any difference here? It was working until a couple days ago. Preview still works! It just doesn't seem to be retrieving things properly on the front end.

We're on PHP 7.4 if it matters, and if you're on Discord you can find me over there -- adrienneleigh#8321

**Comment by adrienne** [comment]
Okay, so, this turned out to be a user error that coincided with the upgrade. Turns out you can't add the block to the eager-loading array, or everything goes boom.
