### ISSUE TITLE
Having all kinds of issues with 1.3.12

### ISSUE THREAD

**Issue by adrienne** [wrav/oembed#92]
Blank fields show our main website in the Preview, which is confusing the heck out of everyone! (The changelog seems to indicate that you fixed that, except it isn't fixed for us.)

Also, a lot of sites don't seem to work at all anymore, including (as mentioned in an earlier issue) Facebook.

**Comment by adrienne** [comment]
Never mind, still being tracked in a different issue. Disregard, i'm closing this as duplicate and thinking i should've checked better!

**Comment by reganlawton** [comment]
No problem I'm just glad its been resolved 😊
