### ISSUE TITLE
"Please check your URL" but is still a valid field when saving entry

### ISSUE THREAD

**Issue by ThinkGraphical** [wrav/oembed#94]
When you for ex. fill in a private IG url in the embed field, there's a "Please check your URL" warning.
But when you click save, the field is accepted as valid (not throwing an error preventing the entry to be saved).

This means the user is unaware that there's something wrong. And possibly breaking stuff in the front, GraphQl, ...

Can we invalidate the field? Or is there a specific reason why not?

**Comment by reganlawton** [comment]
@ThinkGraphical  The issue for this is you send it to a backend API so not session is recorded to the URL, showing 404. When get the Fallback URL it uses the current user session in the iframe so it ISN'T 404'd, this isn't the embed but the fallback iframe of the original URL.

The question I'll need to look into iss the handling of the auth for instagram. I DO know that my upcoming refactor to EMbed v4 has `access_token` support for instagram but I'm unsure about the current v3 support.

**Comment by reganlawton** [comment]
Closing to point to #129
