### ISSUE TITLE
I think you're going to have to upgrade to oembed 4 soon

### ISSUE THREAD

**Issue by adrienne** [wrav/oembed#95]
@reganlawton - fyi. Other addons are starting to require it, and it's getting to be a dependency tree mess. :(

**Comment by reganlawton** [comment]
@adrienne Just FYI I've started this mission it's a major version with breaking changes so I'll be working it and have a version ASAP.

**Comment by reganlawton** [comment]
How you looked into the https://github.com/wrav/oembed/pull/97 PR I haven't been able to get people to look into it more for review.

**Comment by adrienne** [comment]
@reganlawton any updates on this?

**Comment by reganlawton** [comment]
I'll have to re-look into the PR I never got any feedback on the PR and had been hesitant to merge it. I'll have to reconfirm everything and maybe I'll look at pushing it out.

**Comment by adrienne** [comment]
@reganlawton well, it's not compatible as-is with your Craft 4 upgrades, but if you patch it up, i'll definitely review it for you.

**Comment by reganlawton** [comment]
Yeah I need to rework it completely.

**Comment by reganlawton** [comment]
@adrienne Ok a complete new branch and composer tag to test. 

You can use compose.json with the following tag: [dev-feature/embed-v4](https://packagist.org/packages/wrav/oembed#dev-feature/embed-v4)

If you can test that'd be great
