### ISSUE TITLE
Video Privacy and oEmbed referer retrieval

### ISSUE THREAD

**Issue by kisonay** [wrav/oembed#98]
I would like to propose that when the plugin reaches out to retrieve the oembed information that it sets the appropriate domain so that it can retrieve all information.

Right now if videos have privacy settings only allowing it on a specific domain, that domain isn't used when retrieving the information and a lot of information is missing.

**Comment by kisonay** [comment]
Doing some additional investigation, it appears the library oembed makes the call, I see the issue opened there:

https://github.com/oscarotero/Embed/issues/377

**Comment by kisonay** [comment]
I see your plugin is using an version that is a year old 3.3 can we update this to the latest version to hopefully address the issue?

**Comment by kisonay** [comment]
OK some additional information.

This block of code seems to append the referrer as expected.

```
 $dispatcher = new CurlDispatcher([
                CURLOPT_REFERER => UrlHelper::siteUrl(),
            ]);

            /** @var Adapter $media */
            $media = Embed::create($url, $options, $dispatcher);
```

but something else I am noticing is that the field.media is not returning everything it retrieves from the oembed api. Its missing thumbnail.

**Comment by reganlawton** [comment]
I'm currently in the progress of updating the core package to v4 so this should be looked into the new version. Unless I get a PR for the current v3.

**Comment by reganlawton** [comment]
Storey @kisonay i just noticed the PR 😂 I legit just woke up I should have had coffee first 😅

**Comment by kisonay** [comment]
@reganlawton if your interested in including this in v3, I created this PR.

https://github.com/wrav/oembed/pull/99

If there are any changes required, let me know. (I'm no PHP expert.)

**Comment by reganlawton** [comment]
Just in a meeting that started but once its over I'll check the plugin code and be sure its all right and push it out if its all G 👍

**Comment by reganlawton** [comment]
@kisonay That's supporting the tag `dev-master` ATM seems to be working on my end lets see if we have any issues before tagging it. If your happy we can close?

**Comment by kisonay** [comment]
@reganlawton :dev-master is working great on my end. I appreciate the fast turn around and am looking forward to the v4 update.
